-- ============================================================================
-- Wikidata schema for MariaDB
-- Production-oriented DDL for:
--   - core entity tables
--   - property metadata cache
--   - 2-level statement/value architecture
--   - media resolution layer
--
-- Important note:
--   This DDL enforces:
--     * one row max per statement in each child table
--     * FK from child value tables to T_WC_WIKIDATA_STATEMENT
--   But SQL alone does NOT fully enforce:
--     * "each statement must exist in one and only one child table"
--   That final rule should be enforced by application logic and/or triggers.
--
-- Important design choice:
--   There is intentionally NO FK from T_WC_WIKIDATA_ITEM_VALUE.ID_ITEM
--   to T_WC_WIKIDATA_ITEM, because T_WC_WIKIDATA_ITEM is a selective cache.
-- ============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ============================================================================
-- 1. CORE ENTITY TABLES
-- ============================================================================

DROP TABLE IF EXISTS T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK;
DROP TABLE IF EXISTS T_WC_WIKIDATA_MEDIA_RESOURCE_URL;
DROP TABLE IF EXISTS T_WC_WIKIDATA_MEDIA_RESOURCE;

DROP TABLE IF EXISTS T_WC_WIKIDATA_QUANTITY_VALUE;
DROP TABLE IF EXISTS T_WC_WIKIDATA_TIME_VALUE;
DROP TABLE IF EXISTS T_WC_WIKIDATA_MEDIA_VALUE;
DROP TABLE IF EXISTS T_WC_WIKIDATA_EXTERNAL_ID_VALUE;
DROP TABLE IF EXISTS T_WC_WIKIDATA_STRING_VALUE;
DROP TABLE IF EXISTS T_WC_WIKIDATA_ITEM_VALUE;
DROP TABLE IF EXISTS T_WC_WIKIDATA_STATEMENT;

DROP TABLE IF EXISTS T_WC_WIKIDATA_PROPERTY_METADATA;

DROP TABLE IF EXISTS T_WC_WIKIDATA_ITEM;
DROP TABLE IF EXISTS T_WC_WIKIDATA_PERSON;
DROP TABLE IF EXISTS T_WC_WIKIDATA_SERIE;
DROP TABLE IF EXISTS T_WC_WIKIDATA_MOVIE;


CREATE TABLE T_WC_WIKIDATA_MOVIE (
    ID_ROW              BIGINT NOT NULL AUTO_INCREMENT,
    ID_WIKIDATA         VARCHAR(50) NOT NULL,
    LABEL_EN            VARCHAR(500) DEFAULT NULL,
    DESCRIPTION_EN      TEXT DEFAULT NULL,
    LABELS_JSON         LONGTEXT DEFAULT NULL,
    DESCRIPTIONS_JSON   LONGTEXT DEFAULT NULL,
    DELETED             TINYINT(1) DEFAULT 0,
    DAT_CREAT           DATETIME DEFAULT CURRENT_TIMESTAMP,
    TIM_UPDATED         DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_ROW),
    UNIQUE KEY UK_T_WC_WIKIDATA_MOVIE_ID_WIKIDATA (ID_WIKIDATA),
    KEY IDX_T_WC_WIKIDATA_MOVIE_LABEL_EN (LABEL_EN(255)),
    KEY IDX_T_WC_WIKIDATA_MOVIE_DELETED (DELETED)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE T_WC_WIKIDATA_SERIE (
    ID_ROW              BIGINT NOT NULL AUTO_INCREMENT,
    ID_WIKIDATA         VARCHAR(50) NOT NULL,
    LABEL_EN            VARCHAR(500) DEFAULT NULL,
    DESCRIPTION_EN      TEXT DEFAULT NULL,
    LABELS_JSON         LONGTEXT DEFAULT NULL,
    DESCRIPTIONS_JSON   LONGTEXT DEFAULT NULL,
    DELETED             TINYINT(1) DEFAULT 0,
    DAT_CREAT           DATETIME DEFAULT CURRENT_TIMESTAMP,
    TIM_UPDATED         DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_ROW),
    UNIQUE KEY UK_T_WC_WIKIDATA_SERIE_ID_WIKIDATA (ID_WIKIDATA),
    KEY IDX_T_WC_WIKIDATA_SERIE_LABEL_EN (LABEL_EN(255)),
    KEY IDX_T_WC_WIKIDATA_SERIE_DELETED (DELETED)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE T_WC_WIKIDATA_PERSON (
    ID_ROW              BIGINT NOT NULL AUTO_INCREMENT,
    ID_WIKIDATA         VARCHAR(50) NOT NULL,
    LABEL_EN            VARCHAR(500) DEFAULT NULL,
    DESCRIPTION_EN      TEXT DEFAULT NULL,
    LABELS_JSON         LONGTEXT DEFAULT NULL,
    DESCRIPTIONS_JSON   LONGTEXT DEFAULT NULL,
    DELETED             TINYINT(1) DEFAULT 0,
    DAT_CREAT           DATETIME DEFAULT CURRENT_TIMESTAMP,
    TIM_UPDATED         DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_ROW),
    UNIQUE KEY UK_T_WC_WIKIDATA_PERSON_ID_WIKIDATA (ID_WIKIDATA),
    KEY IDX_T_WC_WIKIDATA_PERSON_LABEL_EN (LABEL_EN(255)),
    KEY IDX_T_WC_WIKIDATA_PERSON_DELETED (DELETED)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE T_WC_WIKIDATA_ITEM (
    ID_ROW              BIGINT NOT NULL AUTO_INCREMENT,
    ID_WIKIDATA         VARCHAR(50) NOT NULL,
    LABEL_EN            VARCHAR(500) DEFAULT NULL,
    DESCRIPTION_EN      TEXT DEFAULT NULL,
    LABELS_JSON         LONGTEXT DEFAULT NULL,
    DESCRIPTIONS_JSON   LONGTEXT DEFAULT NULL,
    DELETED             TINYINT(1) DEFAULT 0,
    DAT_CREAT           DATETIME DEFAULT CURRENT_TIMESTAMP,
    TIM_UPDATED         DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_ROW),
    UNIQUE KEY UK_T_WC_WIKIDATA_ITEM_ID_WIKIDATA (ID_WIKIDATA),
    KEY IDX_T_WC_WIKIDATA_ITEM_LABEL_EN (LABEL_EN(255)),
    KEY IDX_T_WC_WIKIDATA_ITEM_DELETED (DELETED)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- ============================================================================
-- 2. PROPERTY METADATA CACHE
-- ============================================================================

CREATE TABLE T_WC_WIKIDATA_PROPERTY_METADATA (
    ID_ROW                  BIGINT NOT NULL AUTO_INCREMENT,
    ID_PROPERTY             VARCHAR(50) NOT NULL,
    PROPERTY_LABEL          VARCHAR(500) DEFAULT NULL,
    PROPERTY_DESCRIPTION    TEXT DEFAULT NULL,
    WIKIDATA_DATATYPE       VARCHAR(100) DEFAULT NULL,
    LOCAL_VALUE_TYPE        ENUM('item','string','external_id','media','time','quantity') DEFAULT NULL,
    EXPECTED_CHILD_TABLE    VARCHAR(100) DEFAULT NULL,
    FORMATTER_URL           TEXT DEFAULT NULL,
    FORMATTER_URI_FOR_RDF   TEXT DEFAULT NULL,
    IS_SUPPORTED            TINYINT(1) NOT NULL DEFAULT 1,
    IS_ACTIVE               TINYINT(1) NOT NULL DEFAULT 1,
    LAST_SYNC_AT            DATETIME DEFAULT NULL,
    DELETED                 TINYINT(1) DEFAULT 0,
    DAT_CREAT               DATETIME DEFAULT CURRENT_TIMESTAMP,
    TIM_UPDATED             DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_ROW),
    UNIQUE KEY UK_T_WC_WIKIDATA_PROPERTY_METADATA_ID_PROPERTY (ID_PROPERTY),
    KEY IDX_T_WC_WIKIDATA_PROPERTY_METADATA_LOCAL_VALUE_TYPE (LOCAL_VALUE_TYPE),
    KEY IDX_T_WC_WIKIDATA_PROPERTY_METADATA_WIKIDATA_DATATYPE (WIKIDATA_DATATYPE),
    KEY IDX_T_WC_WIKIDATA_PROPERTY_METADATA_IS_SUPPORTED (IS_SUPPORTED),
    KEY IDX_T_WC_WIKIDATA_PROPERTY_METADATA_IS_ACTIVE (IS_ACTIVE),
    KEY IDX_T_WC_WIKIDATA_PROPERTY_METADATA_DELETED (DELETED)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- ============================================================================
-- 3. PARENT STATEMENT TABLE
-- ============================================================================

CREATE TABLE T_WC_WIKIDATA_STATEMENT (
    ID_STATEMENT         BIGINT NOT NULL AUTO_INCREMENT,
    ID_WIKIDATA          VARCHAR(50) NOT NULL,
    ID_PROPERTY          VARCHAR(50) NOT NULL,
    STATEMENT_GUID       VARCHAR(255) DEFAULT NULL,
    STATEMENT_HASH       VARCHAR(255) DEFAULT NULL,
    VALUE_TYPE           ENUM('item','string','external_id','media','time','quantity') NOT NULL,
    WIKIDATA_DATATYPE    VARCHAR(100) DEFAULT NULL,
    RANK                 ENUM('preferred','normal','deprecated') DEFAULT NULL,
    IS_BEST_VALUE        TINYINT(1) DEFAULT NULL,
    DISPLAY_ORDER        INT DEFAULT NULL,
    DELETED              TINYINT(1) DEFAULT 0,
    DAT_CREAT            DATETIME DEFAULT CURRENT_TIMESTAMP,
    TIM_UPDATED          DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ID_CREATOR           BIGINT DEFAULT NULL,
    ID_OWNER             BIGINT DEFAULT NULL,
    ID_USER_UPDATED      BIGINT DEFAULT NULL,
    IMPORT_SOURCE        VARCHAR(100) DEFAULT NULL,
    IMPORT_BATCH_ID      VARCHAR(100) DEFAULT NULL,
    LAST_SYNC_AT         DATETIME DEFAULT NULL,
    IS_VALID             TINYINT(1) DEFAULT NULL,
    VALIDATION_ERROR     TEXT DEFAULT NULL,
    RAW_VALUE_TEXT       TEXT DEFAULT NULL,
    PRIMARY KEY (ID_STATEMENT),
    UNIQUE KEY UK_T_WC_WIKIDATA_STATEMENT_GUID (STATEMENT_GUID),
    UNIQUE KEY UK_T_WC_WIKIDATA_STATEMENT_HASH (STATEMENT_HASH),
    KEY IDX_T_WC_WIKIDATA_STATEMENT_ID_WIKIDATA (ID_WIKIDATA),
    KEY IDX_T_WC_WIKIDATA_STATEMENT_ID_PROPERTY (ID_PROPERTY),
    KEY IDX_T_WC_WIKIDATA_STATEMENT_VALUE_TYPE (VALUE_TYPE),
    KEY IDX_T_WC_WIKIDATA_STATEMENT_RANK (RANK),
    KEY IDX_T_WC_WIKIDATA_STATEMENT_IMPORT_BATCH_ID (IMPORT_BATCH_ID),
    KEY IDX_T_WC_WIKIDATA_STATEMENT_DELETED (DELETED),
    KEY IDX_T_WC_WIKIDATA_STATEMENT_WIKIDATA_PROPERTY (ID_WIKIDATA, ID_PROPERTY),
    KEY IDX_T_WC_WIKIDATA_STATEMENT_WIKIDATA_VALUE_TYPE (ID_WIKIDATA, VALUE_TYPE),
    CONSTRAINT FK_T_WC_WIKIDATA_STATEMENT_PROPERTY_METADATA
        FOREIGN KEY (ID_PROPERTY)
        REFERENCES T_WC_WIKIDATA_PROPERTY_METADATA (ID_PROPERTY)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- ============================================================================
-- 4. TYPED VALUE TABLES
-- Each child table uses ID_STATEMENT as PK to guarantee max one row per table.
-- ============================================================================

CREATE TABLE T_WC_WIKIDATA_ITEM_VALUE (
    ID_STATEMENT         BIGINT NOT NULL,
    ID_ITEM              VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_STATEMENT),
    KEY IDX_T_WC_WIKIDATA_ITEM_VALUE_ID_ITEM (ID_ITEM),
    KEY IDX_T_WC_WIKIDATA_ITEM_VALUE_STATEMENT_ITEM (ID_STATEMENT, ID_ITEM),
    CONSTRAINT FK_T_WC_WIKIDATA_ITEM_VALUE_STATEMENT
        FOREIGN KEY (ID_STATEMENT)
        REFERENCES T_WC_WIKIDATA_STATEMENT (ID_STATEMENT)
        ON UPDATE CASCADE
        ON DELETE CASCADE
    -- IMPORTANT: no FK to T_WC_WIKIDATA_ITEM by design
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE T_WC_WIKIDATA_STRING_VALUE (
    ID_STATEMENT             BIGINT NOT NULL,
    VALUE_STRING             LONGTEXT NOT NULL,
    VALUE_STRING_NORMALIZED  LONGTEXT DEFAULT NULL,
    LANG_CODE                VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY (ID_STATEMENT),
    KEY IDX_T_WC_WIKIDATA_STRING_VALUE_LANG_CODE (LANG_CODE),
    CONSTRAINT FK_T_WC_WIKIDATA_STRING_VALUE_STATEMENT
        FOREIGN KEY (ID_STATEMENT)
        REFERENCES T_WC_WIKIDATA_STATEMENT (ID_STATEMENT)
        ON UPDATE CASCADE
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE T_WC_WIKIDATA_EXTERNAL_ID_VALUE (
    ID_STATEMENT                 BIGINT NOT NULL,
    VALUE_EXTERNAL_ID            VARCHAR(1000) NOT NULL,
    VALUE_EXTERNAL_ID_NORMALIZED VARCHAR(1000) DEFAULT NULL,
    FORMATTER_URL                TEXT DEFAULT NULL,
    FORMATTER_URI_RDF            TEXT DEFAULT NULL,
    VALIDATION_STATUS            VARCHAR(100) DEFAULT NULL,
    PRIMARY KEY (ID_STATEMENT),
    KEY IDX_T_WC_WIKIDATA_EXTERNAL_ID_VALUE_NORMALIZED (VALUE_EXTERNAL_ID_NORMALIZED(255)),
    KEY IDX_T_WC_WIKIDATA_EXTERNAL_ID_VALUE_STATUS (VALIDATION_STATUS),
    CONSTRAINT FK_T_WC_WIKIDATA_EXTERNAL_ID_VALUE_STATEMENT
        FOREIGN KEY (ID_STATEMENT)
        REFERENCES T_WC_WIKIDATA_STATEMENT (ID_STATEMENT)
        ON UPDATE CASCADE
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE T_WC_WIKIDATA_MEDIA_VALUE (
    ID_STATEMENT         BIGINT NOT NULL,
    FILE_NAME            VARCHAR(1000) NOT NULL,
    MEDIA_REPOSITORY     VARCHAR(100) DEFAULT NULL,
    FILE_PAGE_URL        TEXT DEFAULT NULL,
    FILE_DIRECT_URL      TEXT DEFAULT NULL,
    MIME_TYPE            VARCHAR(255) DEFAULT NULL,
    FILE_EXTENSION       VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY (ID_STATEMENT),
    KEY IDX_T_WC_WIKIDATA_MEDIA_VALUE_FILE_NAME (FILE_NAME(255)),
    KEY IDX_T_WC_WIKIDATA_MEDIA_VALUE_MEDIA_REPOSITORY (MEDIA_REPOSITORY),
    KEY IDX_T_WC_WIKIDATA_MEDIA_VALUE_MIME_TYPE (MIME_TYPE),
    CONSTRAINT FK_T_WC_WIKIDATA_MEDIA_VALUE_STATEMENT
        FOREIGN KEY (ID_STATEMENT)
        REFERENCES T_WC_WIKIDATA_STATEMENT (ID_STATEMENT)
        ON UPDATE CASCADE
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE T_WC_WIKIDATA_TIME_VALUE (
    ID_STATEMENT         BIGINT NOT NULL,
    RAW_TIME_VALUE       VARCHAR(100) DEFAULT NULL,
    TIME_PRECISION       INT DEFAULT NULL,
    CALENDAR_MODEL       VARCHAR(255) DEFAULT NULL,
    TIMEZONE_OFFSET      INT DEFAULT NULL,
    YEAR_VALUE           INT DEFAULT NULL,
    MONTH_VALUE          INT DEFAULT NULL,
    DAY_VALUE            INT DEFAULT NULL,
    DATE_START           DATE DEFAULT NULL,
    DATE_END             DATE DEFAULT NULL,
    PRIMARY KEY (ID_STATEMENT),
    KEY IDX_T_WC_WIKIDATA_TIME_VALUE_YEAR (YEAR_VALUE),
    KEY IDX_T_WC_WIKIDATA_TIME_VALUE_MONTH (MONTH_VALUE),
    KEY IDX_T_WC_WIKIDATA_TIME_VALUE_DAY (DAY_VALUE),
    KEY IDX_T_WC_WIKIDATA_TIME_VALUE_DATE_START (DATE_START),
    KEY IDX_T_WC_WIKIDATA_TIME_VALUE_DATE_END (DATE_END),
    KEY IDX_T_WC_WIKIDATA_TIME_VALUE_PRECISION (TIME_PRECISION),
    CONSTRAINT FK_T_WC_WIKIDATA_TIME_VALUE_STATEMENT
        FOREIGN KEY (ID_STATEMENT)
        REFERENCES T_WC_WIKIDATA_STATEMENT (ID_STATEMENT)
        ON UPDATE CASCADE
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE T_WC_WIKIDATA_QUANTITY_VALUE (
    ID_STATEMENT         BIGINT NOT NULL,
    AMOUNT               DECIMAL(30,10) DEFAULT NULL,
    UNIT_ID_WIKIDATA     VARCHAR(50) DEFAULT NULL,
    LOWER_BOUND          DECIMAL(30,10) DEFAULT NULL,
    UPPER_BOUND          DECIMAL(30,10) DEFAULT NULL,
    AMOUNT_NORMALIZED    DECIMAL(30,10) DEFAULT NULL,
    DISPLAY_VALUE        VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (ID_STATEMENT),
    KEY IDX_T_WC_WIKIDATA_QUANTITY_VALUE_AMOUNT (AMOUNT),
    KEY IDX_T_WC_WIKIDATA_QUANTITY_VALUE_UNIT (UNIT_ID_WIKIDATA),
    KEY IDX_T_WC_WIKIDATA_QUANTITY_VALUE_AMOUNT_NORMALIZED (AMOUNT_NORMALIZED),
    CONSTRAINT FK_T_WC_WIKIDATA_QUANTITY_VALUE_STATEMENT
        FOREIGN KEY (ID_STATEMENT)
        REFERENCES T_WC_WIKIDATA_STATEMENT (ID_STATEMENT)
        ON UPDATE CASCADE
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- ============================================================================
-- 5. MEDIA RESOLUTION LAYER
-- ============================================================================

CREATE TABLE T_WC_WIKIDATA_MEDIA_RESOURCE (
    ID_MEDIA_RESOURCE            BIGINT NOT NULL AUTO_INCREMENT,
    ID_STATEMENT                 BIGINT NOT NULL,
    ID_WIKIDATA                  VARCHAR(50) NOT NULL,
    ID_PROPERTY                  VARCHAR(50) NOT NULL,
    SOURCE_PLATFORM              ENUM('commons','internet_archive','youtube') NOT NULL,
    SOURCE_IDENTIFIER            VARCHAR(1000) NOT NULL,
    SOURCE_IDENTIFIER_NORMALIZED VARCHAR(1000) DEFAULT NULL,
    RESOURCE_KEY                 VARCHAR(1200) DEFAULT NULL,
    RESOURCE_KIND                ENUM('video','audio','image','document') NOT NULL DEFAULT 'video',
    CONTENT_ROLE                 ENUM('full','trailer','excerpt','clip','interview','unknown') NOT NULL DEFAULT 'unknown',
    CONTENT_SCOPE                ENUM('main_work','related_material','promotional','archival','unknown') NOT NULL DEFAULT 'unknown',
    LANG_CODE                    VARCHAR(20) DEFAULT NULL,
    IS_PREFERRED_RESOURCE        TINYINT(1) NOT NULL DEFAULT 0,
    IS_PRIMARY_FOR_ENTITY        TINYINT(1) NOT NULL DEFAULT 0,
    SOURCE_PRIORITY              INT DEFAULT NULL,
    QUALITY_SCORE                DECIMAL(10,4) DEFAULT NULL,
    RESOURCE_TITLE               VARCHAR(1000) DEFAULT NULL,
    RESOURCE_SUBTITLE            VARCHAR(1000) DEFAULT NULL,
    RESOURCE_DESCRIPTION         TEXT DEFAULT NULL,
    CHANNEL_OR_COLLECTION        VARCHAR(1000) DEFAULT NULL,
    THUMBNAIL_URL_PRIMARY        TEXT DEFAULT NULL,
    DURATION_SECONDS             INT DEFAULT NULL,
    WIDTH                        INT DEFAULT NULL,
    HEIGHT                       INT DEFAULT NULL,
    MIME_TYPE_PRIMARY            VARCHAR(255) DEFAULT NULL,
    FILE_EXTENSION_PRIMARY       VARCHAR(50) DEFAULT NULL,
    FILE_SIZE_PRIMARY            BIGINT DEFAULT NULL,
    IS_PLAYABLE                  TINYINT(1) NOT NULL DEFAULT 0,
    IS_DOWNLOADABLE              TINYINT(1) NOT NULL DEFAULT 0,
    IS_EMBEDDABLE                TINYINT(1) NOT NULL DEFAULT 0,
    IS_ACTIVE                    TINYINT(1) NOT NULL DEFAULT 1,
    IS_VALID                     TINYINT(1) DEFAULT NULL,
    RESOLUTION_STATUS            ENUM('resolved','partial','failed','pending','obsolete') NOT NULL DEFAULT 'pending',
    RESOLUTION_METHOD            VARCHAR(100) DEFAULT NULL,
    LAST_RESOLVED_AT             DATETIME DEFAULT NULL,
    LAST_CHECKED_AT              DATETIME DEFAULT NULL,
    LAST_SUCCESS_AT              DATETIME DEFAULT NULL,
    ERROR_CODE                   VARCHAR(100) DEFAULT NULL,
    ERROR_MESSAGE                TEXT DEFAULT NULL,
    IMPORT_BATCH_ID              VARCHAR(100) DEFAULT NULL,
    DISCOVERED_AT                DATETIME DEFAULT CURRENT_TIMESTAMP,
    TIM_UPDATED                  DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ID_USER_UPDATED              BIGINT DEFAULT NULL,
    DELETED                      TINYINT(1) DEFAULT 0,
    PRIMARY KEY (ID_MEDIA_RESOURCE),
    UNIQUE KEY UK_T_WC_WIKIDATA_MEDIA_RESOURCE_STATEMENT_PLATFORM_IDENTIFIER
        (ID_STATEMENT, SOURCE_PLATFORM, SOURCE_IDENTIFIER_NORMALIZED(255)),
    UNIQUE KEY UK_T_WC_WIKIDATA_MEDIA_RESOURCE_RESOURCE_KEY (RESOURCE_KEY(255)),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_ID_STATEMENT (ID_STATEMENT),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_ID_WIKIDATA (ID_WIKIDATA),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_ID_PROPERTY (ID_PROPERTY),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_PLATFORM (SOURCE_PLATFORM),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_ROLE (CONTENT_ROLE),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_STATUS (RESOLUTION_STATUS),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_PREFERRED (IS_PREFERRED_RESOURCE),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_PRIMARY_ENTITY (IS_PRIMARY_FOR_ENTITY),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_ACTIVE (IS_ACTIVE),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_VALID (IS_VALID),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_DELETED (DELETED),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_ENTITY_PLATFORM (ID_WIKIDATA, SOURCE_PLATFORM),
    CONSTRAINT FK_T_WC_WIKIDATA_MEDIA_RESOURCE_STATEMENT
        FOREIGN KEY (ID_STATEMENT)
        REFERENCES T_WC_WIKIDATA_STATEMENT (ID_STATEMENT)
        ON UPDATE CASCADE
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE T_WC_WIKIDATA_MEDIA_RESOURCE_URL (
    ID_MEDIA_RESOURCE_URL   BIGINT NOT NULL AUTO_INCREMENT,
    ID_MEDIA_RESOURCE       BIGINT NOT NULL,
    URL_TYPE                ENUM('page','watch','embed','file','thumbnail','metadata','manifest','subtitle','transcript') NOT NULL,
    URL_ROLE                VARCHAR(100) DEFAULT NULL,
    DISPLAY_ORDER           INT DEFAULT NULL,
    IS_CANONICAL            TINYINT(1) NOT NULL DEFAULT 0,
    IS_PREFERRED            TINYINT(1) NOT NULL DEFAULT 0,
    IS_DIRECT_FILE          TINYINT(1) NOT NULL DEFAULT 0,
    URL                     TEXT NOT NULL,
    URL_NORMALIZED          TEXT DEFAULT NULL,
    URL_HASH                CHAR(64) DEFAULT NULL,
    MIME_TYPE               VARCHAR(255) DEFAULT NULL,
    FILE_EXTENSION          VARCHAR(50) DEFAULT NULL,
    FILE_SIZE               BIGINT DEFAULT NULL,
    WIDTH                   INT DEFAULT NULL,
    HEIGHT                  INT DEFAULT NULL,
    BITRATE                 INT DEFAULT NULL,
    FRAME_RATE              DECIMAL(10,4) DEFAULT NULL,
    VIDEO_CODEC             VARCHAR(255) DEFAULT NULL,
    AUDIO_CODEC             VARCHAR(255) DEFAULT NULL,
    DURATION_SECONDS        INT DEFAULT NULL,
    QUALITY_LABEL           VARCHAR(100) DEFAULT NULL,
    IS_ACTIVE               TINYINT(1) NOT NULL DEFAULT 1,
    IS_PLAYABLE             TINYINT(1) NOT NULL DEFAULT 0,
    IS_DOWNLOADABLE         TINYINT(1) NOT NULL DEFAULT 0,
    IS_EMBEDDABLE           TINYINT(1) NOT NULL DEFAULT 0,
    IS_PUBLIC               TINYINT(1) DEFAULT NULL,
    HTTP_STATUS             INT DEFAULT NULL,
    CONTENT_TYPE_HEADER     VARCHAR(255) DEFAULT NULL,
    REDIRECT_URL            TEXT DEFAULT NULL,
    LAST_CHECKED_AT         DATETIME DEFAULT NULL,
    LAST_SUCCESS_AT         DATETIME DEFAULT NULL,
    CHECK_COUNT             INT NOT NULL DEFAULT 0,
    FAIL_COUNT              INT NOT NULL DEFAULT 0,
    ERROR_CODE              VARCHAR(100) DEFAULT NULL,
    ERROR_MESSAGE           TEXT DEFAULT NULL,
    DISCOVERED_AT           DATETIME DEFAULT CURRENT_TIMESTAMP,
    TIM_UPDATED             DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED                 TINYINT(1) DEFAULT 0,
    PRIMARY KEY (ID_MEDIA_RESOURCE_URL),
    UNIQUE KEY UK_T_WC_WIKIDATA_MEDIA_RESOURCE_URL_RESOURCE_HASH
        (ID_MEDIA_RESOURCE, URL_HASH),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_URL_RESOURCE (ID_MEDIA_RESOURCE),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_URL_TYPE (URL_TYPE),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_URL_PREFERRED (IS_PREFERRED),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_URL_CANONICAL (IS_CANONICAL),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_URL_DIRECT_FILE (IS_DIRECT_FILE),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_URL_ACTIVE (IS_ACTIVE),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_URL_PLAYABLE (IS_PLAYABLE),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_URL_DOWNLOADABLE (IS_DOWNLOADABLE),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_URL_HTTP_STATUS (HTTP_STATUS),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_URL_QUALITY_LABEL (QUALITY_LABEL),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_URL_DELETED (DELETED),
    CONSTRAINT FK_T_WC_WIKIDATA_MEDIA_RESOURCE_URL_RESOURCE
        FOREIGN KEY (ID_MEDIA_RESOURCE)
        REFERENCES T_WC_WIKIDATA_MEDIA_RESOURCE (ID_MEDIA_RESOURCE)
        ON UPDATE CASCADE
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK (
    ID_MEDIA_RESOURCE_CHECK BIGINT NOT NULL AUTO_INCREMENT,
    ID_MEDIA_RESOURCE       BIGINT NOT NULL,
    ID_MEDIA_RESOURCE_URL   BIGINT DEFAULT NULL,
    CHECK_SCOPE             ENUM('resource','url') NOT NULL,
    CHECK_TYPE              ENUM('resolve','api_lookup','http_head','http_get','redirect_trace','playability_check','embed_check','metadata_refresh') NOT NULL,
    CHECK_REASON            VARCHAR(100) DEFAULT NULL,
    CHECK_STATUS            ENUM('success','partial','failure') NOT NULL,
    RESULT_CODE             VARCHAR(100) DEFAULT NULL,
    RESULT_SUMMARY          VARCHAR(1000) DEFAULT NULL,
    HTTP_STATUS             INT DEFAULT NULL,
    CONTENT_TYPE_HEADER     VARCHAR(255) DEFAULT NULL,
    REDIRECT_URL            TEXT DEFAULT NULL,
    RESPONSE_TIME_MS        INT DEFAULT NULL,
    OBSERVED_URL            TEXT DEFAULT NULL,
    OBSERVED_MIME_TYPE      VARCHAR(255) DEFAULT NULL,
    OBSERVED_FILE_SIZE      BIGINT DEFAULT NULL,
    OBSERVED_DURATION_SECONDS INT DEFAULT NULL,
    OBSERVED_WIDTH          INT DEFAULT NULL,
    OBSERVED_HEIGHT         INT DEFAULT NULL,
    ERROR_CODE              VARCHAR(100) DEFAULT NULL,
    ERROR_MESSAGE           TEXT DEFAULT NULL,
    RAW_RESPONSE_SNIPPET    TEXT DEFAULT NULL,
    CHECKED_AT              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECKER_NAME            VARCHAR(100) DEFAULT NULL,
    IMPORT_BATCH_ID         VARCHAR(100) DEFAULT NULL,
    PRIMARY KEY (ID_MEDIA_RESOURCE_CHECK),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK_RESOURCE (ID_MEDIA_RESOURCE),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK_RESOURCE_URL (ID_MEDIA_RESOURCE_URL),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK_SCOPE (CHECK_SCOPE),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK_TYPE (CHECK_TYPE),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK_STATUS (CHECK_STATUS),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK_HTTP_STATUS (HTTP_STATUS),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK_CHECKED_AT (CHECKED_AT),
    KEY IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK_IMPORT_BATCH_ID (IMPORT_BATCH_ID),
    CONSTRAINT FK_T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK_RESOURCE
        FOREIGN KEY (ID_MEDIA_RESOURCE)
        REFERENCES T_WC_WIKIDATA_MEDIA_RESOURCE (ID_MEDIA_RESOURCE)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK_RESOURCE_URL
        FOREIGN KEY (ID_MEDIA_RESOURCE_URL)
        REFERENCES T_WC_WIKIDATA_MEDIA_RESOURCE_URL (ID_MEDIA_RESOURCE_URL)
        ON UPDATE CASCADE
        ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


SET FOREIGN_KEY_CHECKS = 1;
