-- ============================================================================
-- Ordered bulk-load SQL script
-- From STG_* tables into final Wikidata tables
-- With INSERT ... SELECT and ON DUPLICATE KEY UPDATE logic
--
-- Assumptions:
--   - Final tables already exist
--   - STG_* tables already exist
--   - Triggers on typed child tables are already in place
--   - Data has already been loaded into STG_* tables
--
-- Important load order:
--   1. property metadata
--   2. entity tables
--   3. statement table
--   4. typed value tables
--   5. media resolution tables
--
-- Important operational note:
--   Set @IMPORT_BATCH_ID before running.
-- ============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 1;

SET @IMPORT_BATCH_ID = 'BATCH_20260309_001';

START TRANSACTION;

-- ============================================================================
-- 1. PROPERTY METADATA
-- ============================================================================

INSERT INTO T_WC_WIKIDATA_PROPERTY_METADATA (
    ID_PROPERTY,
    PROPERTY_LABEL,
    PROPERTY_DESCRIPTION,
    WIKIDATA_DATATYPE,
    LOCAL_VALUE_TYPE,
    EXPECTED_CHILD_TABLE,
    FORMATTER_URL,
    FORMATTER_URI_FOR_RDF,
    IS_SUPPORTED,
    IS_ACTIVE,
    LAST_SYNC_AT,
    DELETED,
    TIM_UPDATED
)
SELECT
    s.ID_PROPERTY,
    s.PROPERTY_LABEL,
    s.PROPERTY_DESCRIPTION,
    s.WIKIDATA_DATATYPE,
    CASE
        WHEN s.LOCAL_VALUE_TYPE IN ('item','string','external_id','media','time','quantity')
            THEN s.LOCAL_VALUE_TYPE
        ELSE NULL
    END AS LOCAL_VALUE_TYPE,
    s.EXPECTED_CHILD_TABLE,
    s.FORMATTER_URL,
    s.FORMATTER_URI_FOR_RDF,
    COALESCE(s.IS_SUPPORTED, 1),
    COALESCE(s.IS_ACTIVE, 1),
    s.LAST_SYNC_AT,
    0,
    NOW()
FROM STG_T_WC_WIKIDATA_PROPERTY_METADATA s
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND s.ROW_STATUS IN ('NEW','VALID')
ON DUPLICATE KEY UPDATE
    PROPERTY_LABEL        = VALUES(PROPERTY_LABEL),
    PROPERTY_DESCRIPTION  = VALUES(PROPERTY_DESCRIPTION),
    WIKIDATA_DATATYPE     = VALUES(WIKIDATA_DATATYPE),
    LOCAL_VALUE_TYPE      = VALUES(LOCAL_VALUE_TYPE),
    EXPECTED_CHILD_TABLE  = VALUES(EXPECTED_CHILD_TABLE),
    FORMATTER_URL         = VALUES(FORMATTER_URL),
    FORMATTER_URI_FOR_RDF = VALUES(FORMATTER_URI_FOR_RDF),
    IS_SUPPORTED          = VALUES(IS_SUPPORTED),
    IS_ACTIVE             = VALUES(IS_ACTIVE),
    LAST_SYNC_AT          = VALUES(LAST_SYNC_AT),
    DELETED               = VALUES(DELETED),
    TIM_UPDATED           = NOW();

UPDATE STG_T_WC_WIKIDATA_PROPERTY_METADATA
SET ROW_STATUS = 'LOADED',
    ERROR_MESSAGE = NULL
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND ROW_STATUS IN ('NEW','VALID');

-- ============================================================================
-- 2. CORE ENTITY TABLES
-- ============================================================================

INSERT INTO T_WC_WIKIDATA_MOVIE (
    ID_WIKIDATA,
    LABEL_EN,
    DESCRIPTION_EN,
    LABELS_JSON,
    DESCRIPTIONS_JSON,
    DELETED,
    TIM_UPDATED
)
SELECT
    s.ID_WIKIDATA,
    s.LABEL_EN,
    s.DESCRIPTION_EN,
    s.LABELS_JSON,
    s.DESCRIPTIONS_JSON,
    0,
    NOW()
FROM STG_T_WC_WIKIDATA_MOVIE s
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND s.ROW_STATUS IN ('NEW','VALID')
ON DUPLICATE KEY UPDATE
    LABEL_EN          = VALUES(LABEL_EN),
    DESCRIPTION_EN    = VALUES(DESCRIPTION_EN),
    LABELS_JSON       = VALUES(LABELS_JSON),
    DESCRIPTIONS_JSON = VALUES(DESCRIPTIONS_JSON),
    DELETED           = VALUES(DELETED),
    TIM_UPDATED       = NOW();

UPDATE STG_T_WC_WIKIDATA_MOVIE
SET ROW_STATUS = 'LOADED',
    ERROR_MESSAGE = NULL
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND ROW_STATUS IN ('NEW','VALID');


INSERT INTO T_WC_WIKIDATA_SERIE (
    ID_WIKIDATA,
    LABEL_EN,
    DESCRIPTION_EN,
    LABELS_JSON,
    DESCRIPTIONS_JSON,
    DELETED,
    TIM_UPDATED
)
SELECT
    s.ID_WIKIDATA,
    s.LABEL_EN,
    s.DESCRIPTION_EN,
    s.LABELS_JSON,
    s.DESCRIPTIONS_JSON,
    0,
    NOW()
FROM STG_T_WC_WIKIDATA_SERIE s
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND s.ROW_STATUS IN ('NEW','VALID')
ON DUPLICATE KEY UPDATE
    LABEL_EN          = VALUES(LABEL_EN),
    DESCRIPTION_EN    = VALUES(DESCRIPTION_EN),
    LABELS_JSON       = VALUES(LABELS_JSON),
    DESCRIPTIONS_JSON = VALUES(DESCRIPTIONS_JSON),
    DELETED           = VALUES(DELETED),
    TIM_UPDATED       = NOW();

UPDATE STG_T_WC_WIKIDATA_SERIE
SET ROW_STATUS = 'LOADED',
    ERROR_MESSAGE = NULL
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND ROW_STATUS IN ('NEW','VALID');


INSERT INTO T_WC_WIKIDATA_PERSON (
    ID_WIKIDATA,
    LABEL_EN,
    DESCRIPTION_EN,
    LABELS_JSON,
    DESCRIPTIONS_JSON,
    DELETED,
    TIM_UPDATED
)
SELECT
    s.ID_WIKIDATA,
    s.LABEL_EN,
    s.DESCRIPTION_EN,
    s.LABELS_JSON,
    s.DESCRIPTIONS_JSON,
    0,
    NOW()
FROM STG_T_WC_WIKIDATA_PERSON s
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND s.ROW_STATUS IN ('NEW','VALID')
ON DUPLICATE KEY UPDATE
    LABEL_EN          = VALUES(LABEL_EN),
    DESCRIPTION_EN    = VALUES(DESCRIPTION_EN),
    LABELS_JSON       = VALUES(LABELS_JSON),
    DESCRIPTIONS_JSON = VALUES(DESCRIPTIONS_JSON),
    DELETED           = VALUES(DELETED),
    TIM_UPDATED       = NOW();

UPDATE STG_T_WC_WIKIDATA_PERSON
SET ROW_STATUS = 'LOADED',
    ERROR_MESSAGE = NULL
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND ROW_STATUS IN ('NEW','VALID');


INSERT INTO T_WC_WIKIDATA_ITEM (
    ID_WIKIDATA,
    LABEL_EN,
    DESCRIPTION_EN,
    LABELS_JSON,
    DESCRIPTIONS_JSON,
    DELETED,
    TIM_UPDATED
)
SELECT
    s.ID_WIKIDATA,
    s.LABEL_EN,
    s.DESCRIPTION_EN,
    s.LABELS_JSON,
    s.DESCRIPTIONS_JSON,
    0,
    NOW()
FROM STG_T_WC_WIKIDATA_ITEM s
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND s.ROW_STATUS IN ('NEW','VALID')
ON DUPLICATE KEY UPDATE
    LABEL_EN          = VALUES(LABEL_EN),
    DESCRIPTION_EN    = VALUES(DESCRIPTION_EN),
    LABELS_JSON       = VALUES(LABELS_JSON),
    DESCRIPTIONS_JSON = VALUES(DESCRIPTIONS_JSON),
    DELETED           = VALUES(DELETED),
    TIM_UPDATED       = NOW();

UPDATE STG_T_WC_WIKIDATA_ITEM
SET ROW_STATUS = 'LOADED',
    ERROR_MESSAGE = NULL
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND ROW_STATUS IN ('NEW','VALID');

-- ============================================================================
-- 3. PARENT STATEMENT TABLE
-- ============================================================================

INSERT INTO T_WC_WIKIDATA_STATEMENT (
    ID_STATEMENT,
    ID_WIKIDATA,
    ID_PROPERTY,
    STATEMENT_GUID,
    STATEMENT_HASH,
    VALUE_TYPE,
    WIKIDATA_DATATYPE,
    RANK,
    IS_BEST_VALUE,
    DISPLAY_ORDER,
    DELETED,
    DAT_CREAT,
    TIM_UPDATED,
    ID_CREATOR,
    ID_OWNER,
    ID_USER_UPDATED,
    IMPORT_SOURCE,
    IMPORT_BATCH_ID,
    LAST_SYNC_AT,
    IS_VALID,
    VALIDATION_ERROR,
    RAW_VALUE_TEXT
)
SELECT
    s.ID_STATEMENT,
    s.ID_WIKIDATA,
    s.ID_PROPERTY,
    s.STATEMENT_GUID,
    s.STATEMENT_HASH,
    CASE
        WHEN s.VALUE_TYPE IN ('item','string','external_id','media','time','quantity')
            THEN s.VALUE_TYPE
        ELSE NULL
    END AS VALUE_TYPE,
    s.WIKIDATA_DATATYPE,
    CASE
        WHEN s.RANK IN ('preferred','normal','deprecated') THEN s.RANK
        ELSE NULL
    END AS RANK,
    s.IS_BEST_VALUE,
    s.DISPLAY_ORDER,
    COALESCE(s.DELETED, 0),
    COALESCE(s.DAT_CREAT, NOW()),
    COALESCE(s.TIM_UPDATED, NOW()),
    s.ID_CREATOR,
    s.ID_OWNER,
    s.ID_USER_UPDATED,
    s.IMPORT_SOURCE,
    COALESCE(s.IMPORT_BATCH_ID, @IMPORT_BATCH_ID),
    s.LAST_SYNC_AT,
    s.IS_VALID,
    s.VALIDATION_ERROR,
    s.RAW_VALUE_TEXT
FROM STG_T_WC_WIKIDATA_STATEMENT s
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND s.ROW_STATUS IN ('NEW','VALID')
ON DUPLICATE KEY UPDATE
    ID_WIKIDATA       = VALUES(ID_WIKIDATA),
    ID_PROPERTY       = VALUES(ID_PROPERTY),
    STATEMENT_GUID    = VALUES(STATEMENT_GUID),
    STATEMENT_HASH    = VALUES(STATEMENT_HASH),
    VALUE_TYPE        = VALUES(VALUE_TYPE),
    WIKIDATA_DATATYPE = VALUES(WIKIDATA_DATATYPE),
    RANK              = VALUES(RANK),
    IS_BEST_VALUE     = VALUES(IS_BEST_VALUE),
    DISPLAY_ORDER     = VALUES(DISPLAY_ORDER),
    DELETED           = VALUES(DELETED),
    DAT_CREAT         = VALUES(DAT_CREAT),
    TIM_UPDATED       = NOW(),
    ID_CREATOR        = VALUES(ID_CREATOR),
    ID_OWNER          = VALUES(ID_OWNER),
    ID_USER_UPDATED   = VALUES(ID_USER_UPDATED),
    IMPORT_SOURCE     = VALUES(IMPORT_SOURCE),
    IMPORT_BATCH_ID   = VALUES(IMPORT_BATCH_ID),
    LAST_SYNC_AT      = VALUES(LAST_SYNC_AT),
    IS_VALID          = VALUES(IS_VALID),
    VALIDATION_ERROR  = VALUES(VALIDATION_ERROR),
    RAW_VALUE_TEXT    = VALUES(RAW_VALUE_TEXT);

UPDATE STG_T_WC_WIKIDATA_STATEMENT
SET ROW_STATUS = 'LOADED',
    ERROR_MESSAGE = NULL
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND ROW_STATUS IN ('NEW','VALID');

-- ============================================================================
-- 4. TYPED VALUE TABLES
-- ============================================================================

INSERT INTO T_WC_WIKIDATA_ITEM_VALUE (
    ID_STATEMENT,
    ID_ITEM
)
SELECT
    s.ID_STATEMENT,
    s.ID_ITEM
FROM STG_T_WC_WIKIDATA_ITEM_VALUE s
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND s.ROW_STATUS IN ('NEW','VALID')
ON DUPLICATE KEY UPDATE
    ID_ITEM = VALUES(ID_ITEM);

UPDATE STG_T_WC_WIKIDATA_ITEM_VALUE
SET ROW_STATUS = 'LOADED',
    ERROR_MESSAGE = NULL
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND ROW_STATUS IN ('NEW','VALID');


INSERT INTO T_WC_WIKIDATA_STRING_VALUE (
    ID_STATEMENT,
    VALUE_STRING,
    VALUE_STRING_NORMALIZED,
    LANG_CODE
)
SELECT
    s.ID_STATEMENT,
    s.VALUE_STRING,
    s.VALUE_STRING_NORMALIZED,
    s.LANG_CODE
FROM STG_T_WC_WIKIDATA_STRING_VALUE s
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND s.ROW_STATUS IN ('NEW','VALID')
ON DUPLICATE KEY UPDATE
    VALUE_STRING            = VALUES(VALUE_STRING),
    VALUE_STRING_NORMALIZED = VALUES(VALUE_STRING_NORMALIZED),
    LANG_CODE               = VALUES(LANG_CODE);

UPDATE STG_T_WC_WIKIDATA_STRING_VALUE
SET ROW_STATUS = 'LOADED',
    ERROR_MESSAGE = NULL
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND ROW_STATUS IN ('NEW','VALID');


INSERT INTO T_WC_WIKIDATA_EXTERNAL_ID_VALUE (
    ID_STATEMENT,
    VALUE_EXTERNAL_ID,
    VALUE_EXTERNAL_ID_NORMALIZED,
    FORMATTER_URL,
    FORMATTER_URI_RDF,
    VALIDATION_STATUS
)
SELECT
    s.ID_STATEMENT,
    s.VALUE_EXTERNAL_ID,
    s.VALUE_EXTERNAL_ID_NORMALIZED,
    s.FORMATTER_URL,
    s.FORMATTER_URI_RDF,
    s.VALIDATION_STATUS
FROM STG_T_WC_WIKIDATA_EXTERNAL_ID_VALUE s
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND s.ROW_STATUS IN ('NEW','VALID')
ON DUPLICATE KEY UPDATE
    VALUE_EXTERNAL_ID            = VALUES(VALUE_EXTERNAL_ID),
    VALUE_EXTERNAL_ID_NORMALIZED = VALUES(VALUE_EXTERNAL_ID_NORMALIZED),
    FORMATTER_URL                = VALUES(FORMATTER_URL),
    FORMATTER_URI_RDF            = VALUES(FORMATTER_URI_RDF),
    VALIDATION_STATUS            = VALUES(VALIDATION_STATUS);

UPDATE STG_T_WC_WIKIDATA_EXTERNAL_ID_VALUE
SET ROW_STATUS = 'LOADED',
    ERROR_MESSAGE = NULL
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND ROW_STATUS IN ('NEW','VALID');


INSERT INTO T_WC_WIKIDATA_MEDIA_VALUE (
    ID_STATEMENT,
    FILE_NAME,
    MEDIA_REPOSITORY,
    FILE_PAGE_URL,
    FILE_DIRECT_URL,
    MIME_TYPE,
    FILE_EXTENSION
)
SELECT
    s.ID_STATEMENT,
    s.FILE_NAME,
    s.MEDIA_REPOSITORY,
    s.FILE_PAGE_URL,
    s.FILE_DIRECT_URL,
    s.MIME_TYPE,
    s.FILE_EXTENSION
FROM STG_T_WC_WIKIDATA_MEDIA_VALUE s
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND s.ROW_STATUS IN ('NEW','VALID')
ON DUPLICATE KEY UPDATE
    FILE_NAME        = VALUES(FILE_NAME),
    MEDIA_REPOSITORY = VALUES(MEDIA_REPOSITORY),
    FILE_PAGE_URL    = VALUES(FILE_PAGE_URL),
    FILE_DIRECT_URL  = VALUES(FILE_DIRECT_URL),
    MIME_TYPE        = VALUES(MIME_TYPE),
    FILE_EXTENSION   = VALUES(FILE_EXTENSION);

UPDATE STG_T_WC_WIKIDATA_MEDIA_VALUE
SET ROW_STATUS = 'LOADED',
    ERROR_MESSAGE = NULL
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND ROW_STATUS IN ('NEW','VALID');


INSERT INTO T_WC_WIKIDATA_TIME_VALUE (
    ID_STATEMENT,
    RAW_TIME_VALUE,
    TIME_PRECISION,
    CALENDAR_MODEL,
    TIMEZONE_OFFSET,
    YEAR_VALUE,
    MONTH_VALUE,
    DAY_VALUE,
    DATE_START,
    DATE_END
)
SELECT
    s.ID_STATEMENT,
    s.RAW_TIME_VALUE,
    s.TIME_PRECISION,
    s.CALENDAR_MODEL,
    s.TIMEZONE_OFFSET,
    s.YEAR_VALUE,
    s.MONTH_VALUE,
    s.DAY_VALUE,
    s.DATE_START,
    s.DATE_END
FROM STG_T_WC_WIKIDATA_TIME_VALUE s
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND s.ROW_STATUS IN ('NEW','VALID')
ON DUPLICATE KEY UPDATE
    RAW_TIME_VALUE  = VALUES(RAW_TIME_VALUE),
    TIME_PRECISION  = VALUES(TIME_PRECISION),
    CALENDAR_MODEL  = VALUES(CALENDAR_MODEL),
    TIMEZONE_OFFSET = VALUES(TIMEZONE_OFFSET),
    YEAR_VALUE      = VALUES(YEAR_VALUE),
    MONTH_VALUE     = VALUES(MONTH_VALUE),
    DAY_VALUE       = VALUES(DAY_VALUE),
    DATE_START      = VALUES(DATE_START),
    DATE_END        = VALUES(DATE_END);

UPDATE STG_T_WC_WIKIDATA_TIME_VALUE
SET ROW_STATUS = 'LOADED',
    ERROR_MESSAGE = NULL
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND ROW_STATUS IN ('NEW','VALID');


INSERT INTO T_WC_WIKIDATA_QUANTITY_VALUE (
    ID_STATEMENT,
    AMOUNT,
    UNIT_ID_WIKIDATA,
    LOWER_BOUND,
    UPPER_BOUND,
    AMOUNT_NORMALIZED,
    DISPLAY_VALUE
)
SELECT
    s.ID_STATEMENT,
    s.AMOUNT,
    s.UNIT_ID_WIKIDATA,
    s.LOWER_BOUND,
    s.UPPER_BOUND,
    s.AMOUNT_NORMALIZED,
    s.DISPLAY_VALUE
FROM STG_T_WC_WIKIDATA_QUANTITY_VALUE s
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND s.ROW_STATUS IN ('NEW','VALID')
ON DUPLICATE KEY UPDATE
    AMOUNT            = VALUES(AMOUNT),
    UNIT_ID_WIKIDATA  = VALUES(UNIT_ID_WIKIDATA),
    LOWER_BOUND       = VALUES(LOWER_BOUND),
    UPPER_BOUND       = VALUES(UPPER_BOUND),
    AMOUNT_NORMALIZED = VALUES(AMOUNT_NORMALIZED),
    DISPLAY_VALUE     = VALUES(DISPLAY_VALUE);

UPDATE STG_T_WC_WIKIDATA_QUANTITY_VALUE
SET ROW_STATUS = 'LOADED',
    ERROR_MESSAGE = NULL
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND ROW_STATUS IN ('NEW','VALID');

-- ============================================================================
-- 5. MEDIA RESOURCE MASTER
-- ============================================================================

INSERT INTO T_WC_WIKIDATA_MEDIA_RESOURCE (
    ID_MEDIA_RESOURCE,
    ID_STATEMENT,
    ID_WIKIDATA,
    ID_PROPERTY,
    SOURCE_PLATFORM,
    SOURCE_IDENTIFIER,
    SOURCE_IDENTIFIER_NORMALIZED,
    RESOURCE_KEY,
    RESOURCE_KIND,
    CONTENT_ROLE,
    CONTENT_SCOPE,
    LANG_CODE,
    IS_PREFERRED_RESOURCE,
    IS_PRIMARY_FOR_ENTITY,
    SOURCE_PRIORITY,
    QUALITY_SCORE,
    RESOURCE_TITLE,
    RESOURCE_SUBTITLE,
    RESOURCE_DESCRIPTION,
    CHANNEL_OR_COLLECTION,
    THUMBNAIL_URL_PRIMARY,
    DURATION_SECONDS,
    WIDTH,
    HEIGHT,
    MIME_TYPE_PRIMARY,
    FILE_EXTENSION_PRIMARY,
    FILE_SIZE_PRIMARY,
    IS_PLAYABLE,
    IS_DOWNLOADABLE,
    IS_EMBEDDABLE,
    IS_ACTIVE,
    IS_VALID,
    RESOLUTION_STATUS,
    RESOLUTION_METHOD,
    LAST_RESOLVED_AT,
    LAST_CHECKED_AT,
    LAST_SUCCESS_AT,
    ERROR_CODE,
    ERROR_MESSAGE,
    IMPORT_BATCH_ID,
    DISCOVERED_AT,
    TIM_UPDATED,
    ID_USER_UPDATED,
    DELETED
)
SELECT
    s.ID_MEDIA_RESOURCE,
    s.ID_STATEMENT,
    s.ID_WIKIDATA,
    s.ID_PROPERTY,
    CASE
        WHEN s.SOURCE_PLATFORM IN ('commons','internet_archive','youtube') THEN s.SOURCE_PLATFORM
        ELSE NULL
    END AS SOURCE_PLATFORM,
    s.SOURCE_IDENTIFIER,
    s.SOURCE_IDENTIFIER_NORMALIZED,
    s.RESOURCE_KEY,
    CASE
        WHEN s.RESOURCE_KIND IN ('video','audio','image','document') THEN s.RESOURCE_KIND
        ELSE 'video'
    END AS RESOURCE_KIND,
    CASE
        WHEN s.CONTENT_ROLE IN ('full','trailer','excerpt','clip','interview','unknown') THEN s.CONTENT_ROLE
        ELSE 'unknown'
    END AS CONTENT_ROLE,
    CASE
        WHEN s.CONTENT_SCOPE IN ('main_work','related_material','promotional','archival','unknown') THEN s.CONTENT_SCOPE
        ELSE 'unknown'
    END AS CONTENT_SCOPE,
    s.LANG_CODE,
    COALESCE(s.IS_PREFERRED_RESOURCE, 0),
    COALESCE(s.IS_PRIMARY_FOR_ENTITY, 0),
    s.SOURCE_PRIORITY,
    s.QUALITY_SCORE,
    s.RESOURCE_TITLE,
    s.RESOURCE_SUBTITLE,
    s.RESOURCE_DESCRIPTION,
    s.CHANNEL_OR_COLLECTION,
    s.THUMBNAIL_URL_PRIMARY,
    s.DURATION_SECONDS,
    s.WIDTH,
    s.HEIGHT,
    s.MIME_TYPE_PRIMARY,
    s.FILE_EXTENSION_PRIMARY,
    s.FILE_SIZE_PRIMARY,
    COALESCE(s.IS_PLAYABLE, 0),
    COALESCE(s.IS_DOWNLOADABLE, 0),
    COALESCE(s.IS_EMBEDDABLE, 0),
    COALESCE(s.IS_ACTIVE, 1),
    s.IS_VALID,
    CASE
        WHEN s.RESOLUTION_STATUS IN ('resolved','partial','failed','pending','obsolete') THEN s.RESOLUTION_STATUS
        ELSE 'pending'
    END AS RESOLUTION_STATUS,
    s.RESOLUTION_METHOD,
    s.LAST_RESOLVED_AT,
    s.LAST_CHECKED_AT,
    s.LAST_SUCCESS_AT,
    s.ERROR_CODE,
    s.ERROR_MESSAGE,
    COALESCE(s.IMPORT_BATCH_ID, @IMPORT_BATCH_ID),
    COALESCE(s.DISCOVERED_AT, NOW()),
    COALESCE(s.TIM_UPDATED, NOW()),
    s.ID_USER_UPDATED,
    COALESCE(s.DELETED, 0)
FROM STG_T_WC_WIKIDATA_MEDIA_RESOURCE s
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND s.ROW_STATUS IN ('NEW','VALID')
ON DUPLICATE KEY UPDATE
    ID_STATEMENT                  = VALUES(ID_STATEMENT),
    ID_WIKIDATA                   = VALUES(ID_WIKIDATA),
    ID_PROPERTY                   = VALUES(ID_PROPERTY),
    SOURCE_PLATFORM               = VALUES(SOURCE_PLATFORM),
    SOURCE_IDENTIFIER             = VALUES(SOURCE_IDENTIFIER),
    SOURCE_IDENTIFIER_NORMALIZED  = VALUES(SOURCE_IDENTIFIER_NORMALIZED),
    RESOURCE_KEY                  = VALUES(RESOURCE_KEY),
    RESOURCE_KIND                 = VALUES(RESOURCE_KIND),
    CONTENT_ROLE                  = VALUES(CONTENT_ROLE),
    CONTENT_SCOPE                 = VALUES(CONTENT_SCOPE),
    LANG_CODE                     = VALUES(LANG_CODE),
    IS_PREFERRED_RESOURCE         = VALUES(IS_PREFERRED_RESOURCE),
    IS_PRIMARY_FOR_ENTITY         = VALUES(IS_PRIMARY_FOR_ENTITY),
    SOURCE_PRIORITY               = VALUES(SOURCE_PRIORITY),
    QUALITY_SCORE                 = VALUES(QUALITY_SCORE),
    RESOURCE_TITLE                = VALUES(RESOURCE_TITLE),
    RESOURCE_SUBTITLE             = VALUES(RESOURCE_SUBTITLE),
    RESOURCE_DESCRIPTION          = VALUES(RESOURCE_DESCRIPTION),
    CHANNEL_OR_COLLECTION         = VALUES(CHANNEL_OR_COLLECTION),
    THUMBNAIL_URL_PRIMARY         = VALUES(THUMBNAIL_URL_PRIMARY),
    DURATION_SECONDS              = VALUES(DURATION_SECONDS),
    WIDTH                         = VALUES(WIDTH),
    HEIGHT                        = VALUES(HEIGHT),
    MIME_TYPE_PRIMARY             = VALUES(MIME_TYPE_PRIMARY),
    FILE_EXTENSION_PRIMARY        = VALUES(FILE_EXTENSION_PRIMARY),
    FILE_SIZE_PRIMARY             = VALUES(FILE_SIZE_PRIMARY),
    IS_PLAYABLE                   = VALUES(IS_PLAYABLE),
    IS_DOWNLOADABLE               = VALUES(IS_DOWNLOADABLE),
    IS_EMBEDDABLE                 = VALUES(IS_EMBEDDABLE),
    IS_ACTIVE                     = VALUES(IS_ACTIVE),
    IS_VALID                      = VALUES(IS_VALID),
    RESOLUTION_STATUS             = VALUES(RESOLUTION_STATUS),
    RESOLUTION_METHOD             = VALUES(RESOLUTION_METHOD),
    LAST_RESOLVED_AT              = VALUES(LAST_RESOLVED_AT),
    LAST_CHECKED_AT               = VALUES(LAST_CHECKED_AT),
    LAST_SUCCESS_AT               = VALUES(LAST_SUCCESS_AT),
    ERROR_CODE                    = VALUES(ERROR_CODE),
    ERROR_MESSAGE                 = VALUES(ERROR_MESSAGE),
    IMPORT_BATCH_ID               = VALUES(IMPORT_BATCH_ID),
    DISCOVERED_AT                 = VALUES(DISCOVERED_AT),
    TIM_UPDATED                   = NOW(),
    ID_USER_UPDATED               = VALUES(ID_USER_UPDATED),
    DELETED                       = VALUES(DELETED);

UPDATE STG_T_WC_WIKIDATA_MEDIA_RESOURCE
SET ROW_STATUS = 'LOADED',
    ERROR_MESSAGE = NULL
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND ROW_STATUS IN ('NEW','VALID');

-- ============================================================================
-- 6. MEDIA RESOURCE URL
-- ============================================================================

INSERT INTO T_WC_WIKIDATA_MEDIA_RESOURCE_URL (
    ID_MEDIA_RESOURCE_URL,
    ID_MEDIA_RESOURCE,
    URL_TYPE,
    URL_ROLE,
    DISPLAY_ORDER,
    IS_CANONICAL,
    IS_PREFERRED,
    IS_DIRECT_FILE,
    URL,
    URL_NORMALIZED,
    URL_HASH,
    MIME_TYPE,
    FILE_EXTENSION,
    FILE_SIZE,
    WIDTH,
    HEIGHT,
    BITRATE,
    FRAME_RATE,
    VIDEO_CODEC,
    AUDIO_CODEC,
    DURATION_SECONDS,
    QUALITY_LABEL,
    IS_ACTIVE,
    IS_PLAYABLE,
    IS_DOWNLOADABLE,
    IS_EMBEDDABLE,
    IS_PUBLIC,
    HTTP_STATUS,
    CONTENT_TYPE_HEADER,
    REDIRECT_URL,
    LAST_CHECKED_AT,
    LAST_SUCCESS_AT,
    CHECK_COUNT,
    FAIL_COUNT,
    ERROR_CODE,
    ERROR_MESSAGE,
    DISCOVERED_AT,
    TIM_UPDATED,
    DELETED
)
SELECT
    s.ID_MEDIA_RESOURCE_URL,
    s.ID_MEDIA_RESOURCE,
    CASE
        WHEN s.URL_TYPE IN ('page','watch','embed','file','thumbnail','metadata','manifest','subtitle','transcript')
            THEN s.URL_TYPE
        ELSE NULL
    END AS URL_TYPE,
    s.URL_ROLE,
    s.DISPLAY_ORDER,
    COALESCE(s.IS_CANONICAL, 0),
    COALESCE(s.IS_PREFERRED, 0),
    COALESCE(s.IS_DIRECT_FILE, 0),
    s.URL,
    s.URL_NORMALIZED,
    s.URL_HASH,
    s.MIME_TYPE,
    s.FILE_EXTENSION,
    s.FILE_SIZE,
    s.WIDTH,
    s.HEIGHT,
    s.BITRATE,
    s.FRAME_RATE,
    s.VIDEO_CODEC,
    s.AUDIO_CODEC,
    s.DURATION_SECONDS,
    s.QUALITY_LABEL,
    COALESCE(s.IS_ACTIVE, 1),
    COALESCE(s.IS_PLAYABLE, 0),
    COALESCE(s.IS_DOWNLOADABLE, 0),
    COALESCE(s.IS_EMBEDDABLE, 0),
    s.IS_PUBLIC,
    s.HTTP_STATUS,
    s.CONTENT_TYPE_HEADER,
    s.REDIRECT_URL,
    s.LAST_CHECKED_AT,
    s.LAST_SUCCESS_AT,
    COALESCE(s.CHECK_COUNT, 0),
    COALESCE(s.FAIL_COUNT, 0),
    s.ERROR_CODE,
    s.ERROR_MESSAGE,
    COALESCE(s.DISCOVERED_AT, NOW()),
    COALESCE(s.TIM_UPDATED, NOW()),
    COALESCE(s.DELETED, 0)
FROM STG_T_WC_WIKIDATA_MEDIA_RESOURCE_URL s
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND s.ROW_STATUS IN ('NEW','VALID')
ON DUPLICATE KEY UPDATE
    ID_MEDIA_RESOURCE   = VALUES(ID_MEDIA_RESOURCE),
    URL_TYPE            = VALUES(URL_TYPE),
    URL_ROLE            = VALUES(URL_ROLE),
    DISPLAY_ORDER       = VALUES(DISPLAY_ORDER),
    IS_CANONICAL        = VALUES(IS_CANONICAL),
    IS_PREFERRED        = VALUES(IS_PREFERRED),
    IS_DIRECT_FILE      = VALUES(IS_DIRECT_FILE),
    URL                 = VALUES(URL),
    URL_NORMALIZED      = VALUES(URL_NORMALIZED),
    URL_HASH            = VALUES(URL_HASH),
    MIME_TYPE           = VALUES(MIME_TYPE),
    FILE_EXTENSION      = VALUES(FILE_EXTENSION),
    FILE_SIZE           = VALUES(FILE_SIZE),
    WIDTH               = VALUES(WIDTH),
    HEIGHT              = VALUES(HEIGHT),
    BITRATE             = VALUES(BITRATE),
    FRAME_RATE          = VALUES(FRAME_RATE),
    VIDEO_CODEC         = VALUES(VIDEO_CODEC),
    AUDIO_CODEC         = VALUES(AUDIO_CODEC),
    DURATION_SECONDS    = VALUES(DURATION_SECONDS),
    QUALITY_LABEL       = VALUES(QUALITY_LABEL),
    IS_ACTIVE           = VALUES(IS_ACTIVE),
    IS_PLAYABLE         = VALUES(IS_PLAYABLE),
    IS_DOWNLOADABLE     = VALUES(IS_DOWNLOADABLE),
    IS_EMBEDDABLE       = VALUES(IS_EMBEDDABLE),
    IS_PUBLIC           = VALUES(IS_PUBLIC),
    HTTP_STATUS         = VALUES(HTTP_STATUS),
    CONTENT_TYPE_HEADER = VALUES(CONTENT_TYPE_HEADER),
    REDIRECT_URL        = VALUES(REDIRECT_URL),
    LAST_CHECKED_AT     = VALUES(LAST_CHECKED_AT),
    LAST_SUCCESS_AT     = VALUES(LAST_SUCCESS_AT),
    CHECK_COUNT         = VALUES(CHECK_COUNT),
    FAIL_COUNT          = VALUES(FAIL_COUNT),
    ERROR_CODE          = VALUES(ERROR_CODE),
    ERROR_MESSAGE       = VALUES(ERROR_MESSAGE),
    DISCOVERED_AT       = VALUES(DISCOVERED_AT),
    TIM_UPDATED         = NOW(),
    DELETED             = VALUES(DELETED);

UPDATE STG_T_WC_WIKIDATA_MEDIA_RESOURCE_URL
SET ROW_STATUS = 'LOADED',
    ERROR_MESSAGE = NULL
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND ROW_STATUS IN ('NEW','VALID');

-- ============================================================================
-- 7. MEDIA RESOURCE CHECK HISTORY
-- ============================================================================

INSERT INTO T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK (
    ID_MEDIA_RESOURCE_CHECK,
    ID_MEDIA_RESOURCE,
    ID_MEDIA_RESOURCE_URL,
    CHECK_SCOPE,
    CHECK_TYPE,
    CHECK_REASON,
    CHECK_STATUS,
    RESULT_CODE,
    RESULT_SUMMARY,
    HTTP_STATUS,
    CONTENT_TYPE_HEADER,
    REDIRECT_URL,
    RESPONSE_TIME_MS,
    OBSERVED_URL,
    OBSERVED_MIME_TYPE,
    OBSERVED_FILE_SIZE,
    OBSERVED_DURATION_SECONDS,
    OBSERVED_WIDTH,
    OBSERVED_HEIGHT,
    ERROR_CODE,
    ERROR_MESSAGE,
    RAW_RESPONSE_SNIPPET,
    CHECKED_AT,
    CHECKER_NAME,
    IMPORT_BATCH_ID
)
SELECT
    s.ID_MEDIA_RESOURCE_CHECK,
    s.ID_MEDIA_RESOURCE,
    s.ID_MEDIA_RESOURCE_URL,
    CASE
        WHEN s.CHECK_SCOPE IN ('resource','url') THEN s.CHECK_SCOPE
        ELSE NULL
    END AS CHECK_SCOPE,
    CASE
        WHEN s.CHECK_TYPE IN ('resolve','api_lookup','http_head','http_get','redirect_trace','playability_check','embed_check','metadata_refresh')
            THEN s.CHECK_TYPE
        ELSE NULL
    END AS CHECK_TYPE,
    s.CHECK_REASON,
    CASE
        WHEN s.CHECK_STATUS IN ('success','partial','failure') THEN s.CHECK_STATUS
        ELSE NULL
    END AS CHECK_STATUS,
    s.RESULT_CODE,
    s.RESULT_SUMMARY,
    s.HTTP_STATUS,
    s.CONTENT_TYPE_HEADER,
    s.REDIRECT_URL,
    s.RESPONSE_TIME_MS,
    s.OBSERVED_URL,
    s.OBSERVED_MIME_TYPE,
    s.OBSERVED_FILE_SIZE,
    s.OBSERVED_DURATION_SECONDS,
    s.OBSERVED_WIDTH,
    s.OBSERVED_HEIGHT,
    s.ERROR_CODE,
    s.ERROR_MESSAGE,
    s.RAW_RESPONSE_SNIPPET,
    COALESCE(s.CHECKED_AT, NOW()),
    s.CHECKER_NAME,
    COALESCE(s.IMPORT_BATCH_ID, @IMPORT_BATCH_ID)
FROM STG_T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK s
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND s.ROW_STATUS IN ('NEW','VALID')
ON DUPLICATE KEY UPDATE
    ID_MEDIA_RESOURCE         = VALUES(ID_MEDIA_RESOURCE),
    ID_MEDIA_RESOURCE_URL     = VALUES(ID_MEDIA_RESOURCE_URL),
    CHECK_SCOPE               = VALUES(CHECK_SCOPE),
    CHECK_TYPE                = VALUES(CHECK_TYPE),
    CHECK_REASON              = VALUES(CHECK_REASON),
    CHECK_STATUS              = VALUES(CHECK_STATUS),
    RESULT_CODE               = VALUES(RESULT_CODE),
    RESULT_SUMMARY            = VALUES(RESULT_SUMMARY),
    HTTP_STATUS               = VALUES(HTTP_STATUS),
    CONTENT_TYPE_HEADER       = VALUES(CONTENT_TYPE_HEADER),
    REDIRECT_URL              = VALUES(REDIRECT_URL),
    RESPONSE_TIME_MS          = VALUES(RESPONSE_TIME_MS),
    OBSERVED_URL              = VALUES(OBSERVED_URL),
    OBSERVED_MIME_TYPE        = VALUES(OBSERVED_MIME_TYPE),
    OBSERVED_FILE_SIZE        = VALUES(OBSERVED_FILE_SIZE),
    OBSERVED_DURATION_SECONDS = VALUES(OBSERVED_DURATION_SECONDS),
    OBSERVED_WIDTH            = VALUES(OBSERVED_WIDTH),
    OBSERVED_HEIGHT           = VALUES(OBSERVED_HEIGHT),
    ERROR_CODE                = VALUES(ERROR_CODE),
    ERROR_MESSAGE             = VALUES(ERROR_MESSAGE),
    RAW_RESPONSE_SNIPPET      = VALUES(RAW_RESPONSE_SNIPPET),
    CHECKED_AT                = VALUES(CHECKED_AT),
    CHECKER_NAME              = VALUES(CHECKER_NAME),
    IMPORT_BATCH_ID           = VALUES(IMPORT_BATCH_ID);

UPDATE STG_T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK
SET ROW_STATUS = 'LOADED',
    ERROR_MESSAGE = NULL
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND ROW_STATUS IN ('NEW','VALID');

COMMIT;
