SET FOREIGN_KEY_CHECKS = 0;

-- Media resolution layer (populated by step 112). Deleted first because
-- T_WC_WIKIDATA_MEDIA_RESOURCE references T_WC_WIKIDATA_STATEMENT.
DELETE FROM T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK;
DELETE FROM T_WC_WIKIDATA_MEDIA_RESOURCE_URL;
DELETE FROM T_WC_WIKIDATA_MEDIA_RESOURCE;

DELETE FROM STG_T_WC_WIKIDATA_QUALIFIER_QUANTITY_VALUE;
DELETE FROM STG_T_WC_WIKIDATA_QUALIFIER_TIME_VALUE;
DELETE FROM STG_T_WC_WIKIDATA_QUALIFIER_MEDIA_VALUE;
DELETE FROM STG_T_WC_WIKIDATA_QUALIFIER_EXTERNAL_ID_VALUE;
DELETE FROM STG_T_WC_WIKIDATA_QUALIFIER_STRING_VALUE;
DELETE FROM STG_T_WC_WIKIDATA_QUALIFIER_ITEM_VALUE;
DELETE FROM STG_T_WC_WIKIDATA_STATEMENT_QUALIFIER;
DELETE FROM STG_T_WC_WIKIDATA_QUANTITY_VALUE;
DELETE FROM STG_T_WC_WIKIDATA_TIME_VALUE;
DELETE FROM STG_T_WC_WIKIDATA_MEDIA_VALUE;
DELETE FROM STG_T_WC_WIKIDATA_EXTERNAL_ID_VALUE;
DELETE FROM STG_T_WC_WIKIDATA_STRING_VALUE;
DELETE FROM STG_T_WC_WIKIDATA_ITEM_VALUE;
DELETE FROM STG_T_WC_WIKIDATA_STATEMENT;
DELETE FROM STG_T_WC_WIKIDATA_ITEM;
DELETE FROM STG_T_WC_WIKIDATA_PERSON;
DELETE FROM STG_T_WC_WIKIDATA_SERIE;
DELETE FROM STG_T_WC_WIKIDATA_MOVIE;
DELETE FROM STG_T_WC_WIKIDATA_PROPERTY_METADATA;

DELETE FROM T_WC_WIKIDATA_QUALIFIER_QUANTITY_VALUE;
DELETE FROM T_WC_WIKIDATA_QUALIFIER_TIME_VALUE;
DELETE FROM T_WC_WIKIDATA_QUALIFIER_MEDIA_VALUE;
DELETE FROM T_WC_WIKIDATA_QUALIFIER_EXTERNAL_ID_VALUE;
DELETE FROM T_WC_WIKIDATA_QUALIFIER_STRING_VALUE;
DELETE FROM T_WC_WIKIDATA_QUALIFIER_ITEM_VALUE;
DELETE FROM T_WC_WIKIDATA_STATEMENT_QUALIFIER;
DELETE FROM T_WC_WIKIDATA_QUANTITY_VALUE;
DELETE FROM T_WC_WIKIDATA_TIME_VALUE;
DELETE FROM T_WC_WIKIDATA_MEDIA_VALUE;
DELETE FROM T_WC_WIKIDATA_EXTERNAL_ID_VALUE;
DELETE FROM T_WC_WIKIDATA_STRING_VALUE;
DELETE FROM T_WC_WIKIDATA_ITEM_VALUE;
DELETE FROM T_WC_WIKIDATA_STATEMENT;
DELETE FROM T_WC_WIKIDATA_ITEM;
DELETE FROM T_WC_WIKIDATA_PERSON;
DELETE FROM T_WC_WIKIDATA_SERIE;
DELETE FROM T_WC_WIKIDATA_MOVIE;
DELETE FROM T_WC_WIKIDATA_PROPERTY_METADATA;

SET FOREIGN_KEY_CHECKS = 1;
