SET NAMES utf8mb4;

SET @IMPORT_BATCH_ID = 'wikidata_full_20260509_1730';

SELECT @IMPORT_BATCH_ID AS IMPORT_BATCH_ID;

SELECT 'STG_T_WC_WIKIDATA_STATEMENT' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM STG_T_WC_WIKIDATA_STATEMENT
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
UNION ALL
SELECT 'STG_T_WC_WIKIDATA_STATEMENT_QUALIFIER' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM STG_T_WC_WIKIDATA_STATEMENT_QUALIFIER
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
UNION ALL
SELECT 'STG_T_WC_WIKIDATA_ITEM_VALUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM STG_T_WC_WIKIDATA_ITEM_VALUE
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
UNION ALL
SELECT 'STG_T_WC_WIKIDATA_STRING_VALUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM STG_T_WC_WIKIDATA_STRING_VALUE
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
UNION ALL
SELECT 'STG_T_WC_WIKIDATA_EXTERNAL_ID_VALUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM STG_T_WC_WIKIDATA_EXTERNAL_ID_VALUE
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
UNION ALL
SELECT 'STG_T_WC_WIKIDATA_MEDIA_VALUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM STG_T_WC_WIKIDATA_MEDIA_VALUE
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
UNION ALL
SELECT 'STG_T_WC_WIKIDATA_TIME_VALUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM STG_T_WC_WIKIDATA_TIME_VALUE
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
UNION ALL
SELECT 'STG_T_WC_WIKIDATA_QUANTITY_VALUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM STG_T_WC_WIKIDATA_QUANTITY_VALUE
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
UNION ALL
SELECT 'STG_T_WC_WIKIDATA_QUALIFIER_ITEM_VALUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM STG_T_WC_WIKIDATA_QUALIFIER_ITEM_VALUE
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
UNION ALL
SELECT 'STG_T_WC_WIKIDATA_QUALIFIER_STRING_VALUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM STG_T_WC_WIKIDATA_QUALIFIER_STRING_VALUE
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
UNION ALL
SELECT 'STG_T_WC_WIKIDATA_QUALIFIER_EXTERNAL_ID_VALUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM STG_T_WC_WIKIDATA_QUALIFIER_EXTERNAL_ID_VALUE
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
UNION ALL
SELECT 'STG_T_WC_WIKIDATA_QUALIFIER_MEDIA_VALUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM STG_T_WC_WIKIDATA_QUALIFIER_MEDIA_VALUE
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
UNION ALL
SELECT 'STG_T_WC_WIKIDATA_QUALIFIER_TIME_VALUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM STG_T_WC_WIKIDATA_QUALIFIER_TIME_VALUE
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
UNION ALL
SELECT 'STG_T_WC_WIKIDATA_QUALIFIER_QUANTITY_VALUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM STG_T_WC_WIKIDATA_QUALIFIER_QUANTITY_VALUE
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
ORDER BY TABLE_NAME;

SELECT ROW_STATUS, COUNT(*) AS ROW_COUNT
FROM STG_T_WC_WIKIDATA_STATEMENT
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
GROUP BY ROW_STATUS
ORDER BY ROW_STATUS;

SELECT ROW_STATUS, COUNT(*) AS ROW_COUNT
FROM STG_T_WC_WIKIDATA_STATEMENT_QUALIFIER
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
GROUP BY ROW_STATUS
ORDER BY ROW_STATUS;

SELECT COUNT(*) AS NULL_BATCH_ID_ROWS
FROM STG_T_WC_WIKIDATA_STATEMENT
WHERE IMPORT_BATCH_ID IS NULL;

SELECT COUNT(*) AS LOADED_STAGING_STATEMENTS
FROM STG_T_WC_WIKIDATA_STATEMENT
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND ROW_STATUS = 'LOADED';

SELECT COUNT(*) AS LOADED_STAGING_QUALIFIERS
FROM STG_T_WC_WIKIDATA_STATEMENT_QUALIFIER
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND ROW_STATUS = 'LOADED';

SELECT 'T_WC_WIKIDATA_STATEMENT' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM T_WC_WIKIDATA_STATEMENT
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
UNION ALL
SELECT 'T_WC_WIKIDATA_STATEMENT_QUALIFIER' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM T_WC_WIKIDATA_STATEMENT_QUALIFIER
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
UNION ALL
SELECT 'T_WC_WIKIDATA_ITEM_VALUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM T_WC_WIKIDATA_ITEM_VALUE v
INNER JOIN T_WC_WIKIDATA_STATEMENT s ON s.ID_STATEMENT = v.ID_STATEMENT
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
UNION ALL
SELECT 'T_WC_WIKIDATA_STRING_VALUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM T_WC_WIKIDATA_STRING_VALUE v
INNER JOIN T_WC_WIKIDATA_STATEMENT s ON s.ID_STATEMENT = v.ID_STATEMENT
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
UNION ALL
SELECT 'T_WC_WIKIDATA_EXTERNAL_ID_VALUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM T_WC_WIKIDATA_EXTERNAL_ID_VALUE v
INNER JOIN T_WC_WIKIDATA_STATEMENT s ON s.ID_STATEMENT = v.ID_STATEMENT
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
UNION ALL
SELECT 'T_WC_WIKIDATA_MEDIA_VALUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM T_WC_WIKIDATA_MEDIA_VALUE v
INNER JOIN T_WC_WIKIDATA_STATEMENT s ON s.ID_STATEMENT = v.ID_STATEMENT
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
UNION ALL
SELECT 'T_WC_WIKIDATA_TIME_VALUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM T_WC_WIKIDATA_TIME_VALUE v
INNER JOIN T_WC_WIKIDATA_STATEMENT s ON s.ID_STATEMENT = v.ID_STATEMENT
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
UNION ALL
SELECT 'T_WC_WIKIDATA_QUANTITY_VALUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM T_WC_WIKIDATA_QUANTITY_VALUE v
INNER JOIN T_WC_WIKIDATA_STATEMENT s ON s.ID_STATEMENT = v.ID_STATEMENT
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
UNION ALL
SELECT 'T_WC_WIKIDATA_QUALIFIER_ITEM_VALUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM T_WC_WIKIDATA_QUALIFIER_ITEM_VALUE v
INNER JOIN T_WC_WIKIDATA_STATEMENT_QUALIFIER q ON q.ID_STATEMENT_QUALIFIER = v.ID_STATEMENT_QUALIFIER
WHERE q.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
UNION ALL
SELECT 'T_WC_WIKIDATA_QUALIFIER_STRING_VALUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM T_WC_WIKIDATA_QUALIFIER_STRING_VALUE v
INNER JOIN T_WC_WIKIDATA_STATEMENT_QUALIFIER q ON q.ID_STATEMENT_QUALIFIER = v.ID_STATEMENT_QUALIFIER
WHERE q.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
UNION ALL
SELECT 'T_WC_WIKIDATA_QUALIFIER_EXTERNAL_ID_VALUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM T_WC_WIKIDATA_QUALIFIER_EXTERNAL_ID_VALUE v
INNER JOIN T_WC_WIKIDATA_STATEMENT_QUALIFIER q ON q.ID_STATEMENT_QUALIFIER = v.ID_STATEMENT_QUALIFIER
WHERE q.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
UNION ALL
SELECT 'T_WC_WIKIDATA_QUALIFIER_MEDIA_VALUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM T_WC_WIKIDATA_QUALIFIER_MEDIA_VALUE v
INNER JOIN T_WC_WIKIDATA_STATEMENT_QUALIFIER q ON q.ID_STATEMENT_QUALIFIER = v.ID_STATEMENT_QUALIFIER
WHERE q.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
UNION ALL
SELECT 'T_WC_WIKIDATA_QUALIFIER_TIME_VALUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM T_WC_WIKIDATA_QUALIFIER_TIME_VALUE v
INNER JOIN T_WC_WIKIDATA_STATEMENT_QUALIFIER q ON q.ID_STATEMENT_QUALIFIER = v.ID_STATEMENT_QUALIFIER
WHERE q.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
UNION ALL
SELECT 'T_WC_WIKIDATA_QUALIFIER_QUANTITY_VALUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM T_WC_WIKIDATA_QUALIFIER_QUANTITY_VALUE v
INNER JOIN T_WC_WIKIDATA_STATEMENT_QUALIFIER q ON q.ID_STATEMENT_QUALIFIER = v.ID_STATEMENT_QUALIFIER
WHERE q.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
ORDER BY TABLE_NAME;

SELECT VALUE_TYPE, COUNT(*) AS ROW_COUNT
FROM T_WC_WIKIDATA_STATEMENT
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
GROUP BY VALUE_TYPE
ORDER BY VALUE_TYPE;

SELECT VALUE_TYPE, COUNT(*) AS ROW_COUNT
FROM T_WC_WIKIDATA_STATEMENT_QUALIFIER
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
GROUP BY VALUE_TYPE
ORDER BY VALUE_TYPE;

SELECT COUNT(*) AS TARGET_STATEMENTS_FOR_BATCH
FROM T_WC_WIKIDATA_STATEMENT
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID;

SELECT COUNT(*) AS TARGET_QUALIFIERS_FOR_BATCH
FROM T_WC_WIKIDATA_STATEMENT_QUALIFIER
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID;
