-- ============================================================================
-- Rechargement des SEULS qualificatifs (WIKIDATA-CRAWLER-019)
-- ============================================================================
--
-- Extrait mecaniquement de la section 4B de 03_bulk_load_from_staging_FULL.sql
-- (lignes 677 a 984). Aucune ligne modifiee : seuls l'en-tete et le COMMIT final
-- sont ajoutes, pour que la section puisse tourner seule.
--
-- POURQUOI. Apres migrations/repair_qualifier_identity.py, seuls les 7 fichiers de
-- qualificatifs ont change. Rejouer l'etape 110 entiere rechargerait aussi les
-- 37 M de statements et les tables d'entites, pour rien : environ 11 h. Cette
-- section ne touche que ce qui a bouge, soit 5,58 M de qualificatifs et autant de
-- valeurs.
--
-- PREREQUIS, dans cet ordre :
--   1. migrations/repair_qualifier_identity.py a tourne sur /shared/pass2 ;
--   2. les 7 tables cibles de qualificatifs sont vides
--      (mariadb vaugouindb < 06_repair_qualifier_tables.sql) ;
--   3. le staging porte les lignes REPAREES pour ce batch, c'est-a-dire :
--        DELETE FROM STG_T_WC_WIKIDATA_STATEMENT_QUALIFIER      WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID;
--        (idem pour les 6 STG_T_WC_WIKIDATA_QUALIFIER_*_VALUE)
--        puis load_staging_jsonl.py --only-table ... (voir AGENTS.md).
--
-- Les statements parents ne sont PAS rechargees : la cle etrangere
-- FK_T_WC_WIKIDATA_STATEMENT_QUALIFIER_STATEMENT exige donc qu'elles soient deja
-- en base, ce qui est le cas puisqu'elles viennent du meme batch.
-- ============================================================================

SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
SET FOREIGN_KEY_CHECKS = 1;
SET SESSION max_statement_time = 0;

-- Doit valoir exactement l'IMPORT_BATCH_ID du .env utilise pour le staging.
SET @IMPORT_BATCH_ID = CONVERT('wikidata_full_20260726_1300' USING utf8mb4) COLLATE utf8mb4_unicode_ci;

-- Garde-fou : si lignes_en_staging vaut 0, le batch est faux ou le staging n'a pas
-- ete recharge. Ne pas continuer, le reste ne ferait rien.
SELECT @IMPORT_BATCH_ID AS batch_utilise,
       (SELECT COUNT(*) FROM STG_T_WC_WIKIDATA_STATEMENT_QUALIFIER
        WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID) AS lignes_en_staging,
       (SELECT COUNT(*) FROM T_WC_WIKIDATA_STATEMENT_QUALIFIER) AS lignes_deja_en_cible;

START TRANSACTION;

-- ============================================================================
-- 4B. STATEMENT QUALIFIERS
-- ============================================================================

INSERT INTO T_WC_WIKIDATA_STATEMENT_QUALIFIER (
    ID_STATEMENT_QUALIFIER,
    ID_STATEMENT,
    ID_QUALIFIER_PROPERTY,
    QUALIFIER_HASH,
    VALUE_TYPE,
    WIKIDATA_DATATYPE,
    DISPLAY_ORDER,
    DELETED,
    DAT_CREAT,
    TIM_UPDATED,
    ID_CREATOR,
    ID_OWNER,
    ID_USER_UPDATED,
    IMPORT_SOURCE,
    IMPORT_BATCH_ID,
    LAST_SYNC_AT,
    IS_VALID,
    VALIDATION_ERROR,
    RAW_VALUE_TEXT
)
SELECT
    s.ID_STATEMENT_QUALIFIER,
    s.ID_STATEMENT,
    s.ID_QUALIFIER_PROPERTY,
    s.QUALIFIER_HASH,
    s.VALUE_TYPE,
    s.WIKIDATA_DATATYPE,
    s.DISPLAY_ORDER,
    COALESCE(s.DELETED, 0),
    COALESCE(s.DAT_CREAT, NOW()),
    COALESCE(s.TIM_UPDATED, NOW()),
    s.ID_CREATOR,
    s.ID_OWNER,
    s.ID_USER_UPDATED,
    s.IMPORT_SOURCE,
    COALESCE(s.IMPORT_BATCH_ID, @IMPORT_BATCH_ID),
    s.LAST_SYNC_AT,
    s.IS_VALID,
    s.VALIDATION_ERROR,
    s.RAW_VALUE_TEXT
FROM STG_T_WC_WIKIDATA_STATEMENT_QUALIFIER s
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND s.ROW_STATUS IN ('NEW','VALID')
ON DUPLICATE KEY UPDATE
    ID_STATEMENT          = VALUES(ID_STATEMENT),
    ID_QUALIFIER_PROPERTY = VALUES(ID_QUALIFIER_PROPERTY),
    QUALIFIER_HASH        = VALUES(QUALIFIER_HASH),
    VALUE_TYPE            = VALUES(VALUE_TYPE),
    WIKIDATA_DATATYPE     = VALUES(WIKIDATA_DATATYPE),
    DISPLAY_ORDER         = VALUES(DISPLAY_ORDER),
    DELETED               = VALUES(DELETED),
    DAT_CREAT             = VALUES(DAT_CREAT),
    TIM_UPDATED           = NOW(),
    ID_CREATOR            = VALUES(ID_CREATOR),
    ID_OWNER              = VALUES(ID_OWNER),
    ID_USER_UPDATED       = VALUES(ID_USER_UPDATED),
    IMPORT_SOURCE         = VALUES(IMPORT_SOURCE),
    IMPORT_BATCH_ID       = VALUES(IMPORT_BATCH_ID),
    LAST_SYNC_AT          = VALUES(LAST_SYNC_AT),
    IS_VALID              = VALUES(IS_VALID),
    VALIDATION_ERROR      = VALUES(VALIDATION_ERROR),
    RAW_VALUE_TEXT        = VALUES(RAW_VALUE_TEXT);

UPDATE STG_T_WC_WIKIDATA_STATEMENT_QUALIFIER
SET ROW_STATUS = 'LOADED',
    ERROR_MESSAGE = NULL
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND ROW_STATUS IN ('NEW','VALID');

-- ----------------------------------------------------------------------------
-- Same VALUE_TYPE-flip purge as section 3B, for the qualifier value tables.
-- ID_STATEMENT_QUALIFIER is deterministic, so a qualifier whose VALUE_TYPE
-- changed between dumps would otherwise trip the qualifier child-table triggers.
-- ----------------------------------------------------------------------------

DELETE v FROM T_WC_WIKIDATA_QUALIFIER_ITEM_VALUE v
 WHERE EXISTS (SELECT 1 FROM STG_T_WC_WIKIDATA_STATEMENT_QUALIFIER s
              WHERE s.ID_STATEMENT_QUALIFIER = v.ID_STATEMENT_QUALIFIER
                AND s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
                AND s.VALUE_TYPE <> 'item');

DELETE v FROM T_WC_WIKIDATA_QUALIFIER_STRING_VALUE v
 WHERE EXISTS (SELECT 1 FROM STG_T_WC_WIKIDATA_STATEMENT_QUALIFIER s
              WHERE s.ID_STATEMENT_QUALIFIER = v.ID_STATEMENT_QUALIFIER
                AND s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
                AND s.VALUE_TYPE <> 'string');

DELETE v FROM T_WC_WIKIDATA_QUALIFIER_EXTERNAL_ID_VALUE v
 WHERE EXISTS (SELECT 1 FROM STG_T_WC_WIKIDATA_STATEMENT_QUALIFIER s
              WHERE s.ID_STATEMENT_QUALIFIER = v.ID_STATEMENT_QUALIFIER
                AND s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
                AND s.VALUE_TYPE <> 'external_id');

DELETE v FROM T_WC_WIKIDATA_QUALIFIER_MEDIA_VALUE v
 WHERE EXISTS (SELECT 1 FROM STG_T_WC_WIKIDATA_STATEMENT_QUALIFIER s
              WHERE s.ID_STATEMENT_QUALIFIER = v.ID_STATEMENT_QUALIFIER
                AND s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
                AND s.VALUE_TYPE <> 'media');

DELETE v FROM T_WC_WIKIDATA_QUALIFIER_TIME_VALUE v
 WHERE EXISTS (SELECT 1 FROM STG_T_WC_WIKIDATA_STATEMENT_QUALIFIER s
              WHERE s.ID_STATEMENT_QUALIFIER = v.ID_STATEMENT_QUALIFIER
                AND s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
                AND s.VALUE_TYPE <> 'time');

DELETE v FROM T_WC_WIKIDATA_QUALIFIER_QUANTITY_VALUE v
 WHERE EXISTS (SELECT 1 FROM STG_T_WC_WIKIDATA_STATEMENT_QUALIFIER s
              WHERE s.ID_STATEMENT_QUALIFIER = v.ID_STATEMENT_QUALIFIER
                AND s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
                AND s.VALUE_TYPE <> 'quantity');


INSERT INTO T_WC_WIKIDATA_QUALIFIER_ITEM_VALUE (
    ID_STATEMENT_QUALIFIER,
    ID_ITEM
)
SELECT
    s.ID_STATEMENT_QUALIFIER,
    s.ID_ITEM
FROM STG_T_WC_WIKIDATA_QUALIFIER_ITEM_VALUE s
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND s.ROW_STATUS IN ('NEW','VALID')
ON DUPLICATE KEY UPDATE
    ID_ITEM = VALUES(ID_ITEM);

UPDATE STG_T_WC_WIKIDATA_QUALIFIER_ITEM_VALUE
SET ROW_STATUS = 'LOADED',
    ERROR_MESSAGE = NULL
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND ROW_STATUS IN ('NEW','VALID');


INSERT INTO T_WC_WIKIDATA_QUALIFIER_STRING_VALUE (
    ID_STATEMENT_QUALIFIER,
    VALUE_STRING,
    VALUE_STRING_NORMALIZED,
    LANG_CODE
)
SELECT
    s.ID_STATEMENT_QUALIFIER,
    s.VALUE_STRING,
    s.VALUE_STRING_NORMALIZED,
    s.LANG_CODE
FROM STG_T_WC_WIKIDATA_QUALIFIER_STRING_VALUE s
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND s.ROW_STATUS IN ('NEW','VALID')
ON DUPLICATE KEY UPDATE
    VALUE_STRING            = VALUES(VALUE_STRING),
    VALUE_STRING_NORMALIZED = VALUES(VALUE_STRING_NORMALIZED),
    LANG_CODE               = VALUES(LANG_CODE);

UPDATE STG_T_WC_WIKIDATA_QUALIFIER_STRING_VALUE
SET ROW_STATUS = 'LOADED',
    ERROR_MESSAGE = NULL
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND ROW_STATUS IN ('NEW','VALID');


INSERT INTO T_WC_WIKIDATA_QUALIFIER_EXTERNAL_ID_VALUE (
    ID_STATEMENT_QUALIFIER,
    VALUE_EXTERNAL_ID,
    VALUE_EXTERNAL_ID_NORMALIZED,
    FORMATTER_URL,
    FORMATTER_URI_RDF,
    VALIDATION_STATUS
)
SELECT
    s.ID_STATEMENT_QUALIFIER,
    s.VALUE_EXTERNAL_ID,
    s.VALUE_EXTERNAL_ID_NORMALIZED,
    s.FORMATTER_URL,
    s.FORMATTER_URI_RDF,
    s.VALIDATION_STATUS
FROM STG_T_WC_WIKIDATA_QUALIFIER_EXTERNAL_ID_VALUE s
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND s.ROW_STATUS IN ('NEW','VALID')
ON DUPLICATE KEY UPDATE
    VALUE_EXTERNAL_ID            = VALUES(VALUE_EXTERNAL_ID),
    VALUE_EXTERNAL_ID_NORMALIZED = VALUES(VALUE_EXTERNAL_ID_NORMALIZED),
    FORMATTER_URL                = VALUES(FORMATTER_URL),
    FORMATTER_URI_RDF            = VALUES(FORMATTER_URI_RDF),
    VALIDATION_STATUS            = VALUES(VALIDATION_STATUS);

UPDATE STG_T_WC_WIKIDATA_QUALIFIER_EXTERNAL_ID_VALUE
SET ROW_STATUS = 'LOADED',
    ERROR_MESSAGE = NULL
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND ROW_STATUS IN ('NEW','VALID');


INSERT INTO T_WC_WIKIDATA_QUALIFIER_MEDIA_VALUE (
    ID_STATEMENT_QUALIFIER,
    FILE_NAME,
    MEDIA_REPOSITORY,
    FILE_PAGE_URL,
    FILE_DIRECT_URL,
    MIME_TYPE,
    FILE_EXTENSION
)
SELECT
    s.ID_STATEMENT_QUALIFIER,
    s.FILE_NAME,
    s.MEDIA_REPOSITORY,
    s.FILE_PAGE_URL,
    s.FILE_DIRECT_URL,
    s.MIME_TYPE,
    s.FILE_EXTENSION
FROM STG_T_WC_WIKIDATA_QUALIFIER_MEDIA_VALUE s
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND s.ROW_STATUS IN ('NEW','VALID')
ON DUPLICATE KEY UPDATE
    FILE_NAME        = VALUES(FILE_NAME),
    MEDIA_REPOSITORY = VALUES(MEDIA_REPOSITORY),
    FILE_PAGE_URL    = VALUES(FILE_PAGE_URL),
    FILE_DIRECT_URL  = VALUES(FILE_DIRECT_URL),
    MIME_TYPE        = VALUES(MIME_TYPE),
    FILE_EXTENSION   = VALUES(FILE_EXTENSION);

UPDATE STG_T_WC_WIKIDATA_QUALIFIER_MEDIA_VALUE
SET ROW_STATUS = 'LOADED',
    ERROR_MESSAGE = NULL
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND ROW_STATUS IN ('NEW','VALID');


INSERT INTO T_WC_WIKIDATA_QUALIFIER_TIME_VALUE (
    ID_STATEMENT_QUALIFIER,
    RAW_TIME_VALUE,
    TIME_PRECISION,
    CALENDAR_MODEL,
    TIMEZONE_OFFSET,
    YEAR_VALUE,
    MONTH_VALUE,
    DAY_VALUE,
    DATE_START,
    DATE_END
)
SELECT
    s.ID_STATEMENT_QUALIFIER,
    s.RAW_TIME_VALUE,
    s.TIME_PRECISION,
    s.CALENDAR_MODEL,
    s.TIMEZONE_OFFSET,
    s.YEAR_VALUE,
    s.MONTH_VALUE,
    s.DAY_VALUE,
    s.DATE_START,
    s.DATE_END
FROM STG_T_WC_WIKIDATA_QUALIFIER_TIME_VALUE s
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND s.ROW_STATUS IN ('NEW','VALID')
ON DUPLICATE KEY UPDATE
    RAW_TIME_VALUE  = VALUES(RAW_TIME_VALUE),
    TIME_PRECISION  = VALUES(TIME_PRECISION),
    CALENDAR_MODEL  = VALUES(CALENDAR_MODEL),
    TIMEZONE_OFFSET = VALUES(TIMEZONE_OFFSET),
    YEAR_VALUE      = VALUES(YEAR_VALUE),
    MONTH_VALUE     = VALUES(MONTH_VALUE),
    DAY_VALUE       = VALUES(DAY_VALUE),
    DATE_START      = VALUES(DATE_START),
    DATE_END        = VALUES(DATE_END);

UPDATE STG_T_WC_WIKIDATA_QUALIFIER_TIME_VALUE
SET ROW_STATUS = 'LOADED',
    ERROR_MESSAGE = NULL
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND ROW_STATUS IN ('NEW','VALID');


INSERT INTO T_WC_WIKIDATA_QUALIFIER_QUANTITY_VALUE (
    ID_STATEMENT_QUALIFIER,
    AMOUNT,
    UNIT_ID_WIKIDATA,
    LOWER_BOUND,
    UPPER_BOUND,
    AMOUNT_NORMALIZED,
    DISPLAY_VALUE
)
SELECT
    s.ID_STATEMENT_QUALIFIER,
    s.AMOUNT,
    s.UNIT_ID_WIKIDATA,
    s.LOWER_BOUND,
    s.UPPER_BOUND,
    s.AMOUNT_NORMALIZED,
    s.DISPLAY_VALUE
FROM STG_T_WC_WIKIDATA_QUALIFIER_QUANTITY_VALUE s
WHERE s.IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND s.ROW_STATUS IN ('NEW','VALID')
ON DUPLICATE KEY UPDATE
    AMOUNT            = VALUES(AMOUNT),
    UNIT_ID_WIKIDATA  = VALUES(UNIT_ID_WIKIDATA),
    LOWER_BOUND       = VALUES(LOWER_BOUND),
    UPPER_BOUND       = VALUES(UPPER_BOUND),
    AMOUNT_NORMALIZED = VALUES(AMOUNT_NORMALIZED),
    DISPLAY_VALUE     = VALUES(DISPLAY_VALUE);

UPDATE STG_T_WC_WIKIDATA_QUALIFIER_QUANTITY_VALUE
SET ROW_STATUS = 'LOADED',
    ERROR_MESSAGE = NULL
WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID
  AND ROW_STATUS IN ('NEW','VALID');

COMMIT;

-- Controle final : les deux comptes doivent etre egaux et valoir 5 577 076 si le
-- staging porte bien la sortie reparee du 2026-07-31.
SELECT (SELECT COUNT(*) FROM T_WC_WIKIDATA_STATEMENT_QUALIFIER) AS qualificatifs_charges,
       (SELECT COUNT(*) FROM STG_T_WC_WIKIDATA_STATEMENT_QUALIFIER
        WHERE IMPORT_BATCH_ID = @IMPORT_BATCH_ID)               AS attendus_depuis_staging;
