-- ============================================================================
-- apply_to_live_db.sql
--
-- Idempotent schema additions for an EXISTING vaugouindb database.
--
-- The canonical schema (01_create_schema.sql) only runs on a fresh database, so
-- a long-lived live DB never picks up newly-added tables. This script brings an
-- existing DB up to date for the SEASON / EPISODE / CHARACTER entity types added
-- to the V2 Wikidata crawler, and re-creates any staging table that is missing.
-- It is safe to run repeatedly: every statement uses CREATE TABLE IF NOT EXISTS
-- and touches nothing that already exists.
--
-- Staging tables are disposable (rebuilt from the ETL NDJSON at step 108) and
-- are routinely dropped by hand to reclaim disk space. Re-creating them here
-- means a dropped STG_* table costs nothing: step 108 restores it in place
-- instead of aborting the run after several days of ETL.
--
-- It is executed automatically at the start of step 108 (load staging) and
-- step 110 (bulk load) by wikidata_crawler.py, so a normal run applies it for
-- free. It can also be run by hand:
--     docker exec -i damp-vaugouin-com-mariadb-1 mariadb -uroot -p \
--         --default-character-set=utf8mb4 vaugouindb < apply_to_live_db.sql
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Target entity tables (mirror T_WC_WIKIDATA_MOVIE in 01_create_schema.sql)
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS T_WC_WIKIDATA_SEASON (
    ID_ROW              BIGINT NOT NULL AUTO_INCREMENT,
    ID_WIKIDATA         VARCHAR(50) NOT NULL,
    LABEL_EN            VARCHAR(500) DEFAULT NULL,
    DESCRIPTION_EN      TEXT DEFAULT NULL,
    LABELS_JSON         LONGTEXT DEFAULT NULL,
    DESCRIPTIONS_JSON   LONGTEXT DEFAULT NULL,
    DELETED             TINYINT(1) DEFAULT 0,
    DAT_CREAT           DATETIME DEFAULT CURRENT_TIMESTAMP,
    TIM_UPDATED         DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_ROW),
    UNIQUE KEY UK_T_WC_WIKIDATA_SEASON_ID_WIKIDATA (ID_WIKIDATA),
    KEY IDX_T_WC_WIKIDATA_SEASON_LABEL_EN (LABEL_EN(255)),
    KEY IDX_T_WC_WIKIDATA_SEASON_DELETED (DELETED)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS T_WC_WIKIDATA_EPISODE (
    ID_ROW              BIGINT NOT NULL AUTO_INCREMENT,
    ID_WIKIDATA         VARCHAR(50) NOT NULL,
    LABEL_EN            VARCHAR(500) DEFAULT NULL,
    DESCRIPTION_EN      TEXT DEFAULT NULL,
    LABELS_JSON         LONGTEXT DEFAULT NULL,
    DESCRIPTIONS_JSON   LONGTEXT DEFAULT NULL,
    DELETED             TINYINT(1) DEFAULT 0,
    DAT_CREAT           DATETIME DEFAULT CURRENT_TIMESTAMP,
    TIM_UPDATED         DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_ROW),
    UNIQUE KEY UK_T_WC_WIKIDATA_EPISODE_ID_WIKIDATA (ID_WIKIDATA),
    KEY IDX_T_WC_WIKIDATA_EPISODE_LABEL_EN (LABEL_EN(255)),
    KEY IDX_T_WC_WIKIDATA_EPISODE_DELETED (DELETED)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS T_WC_WIKIDATA_CHARACTER (
    ID_ROW              BIGINT NOT NULL AUTO_INCREMENT,
    ID_WIKIDATA         VARCHAR(50) NOT NULL,
    LABEL_EN            VARCHAR(500) DEFAULT NULL,
    DESCRIPTION_EN      TEXT DEFAULT NULL,
    LABELS_JSON         LONGTEXT DEFAULT NULL,
    DESCRIPTIONS_JSON   LONGTEXT DEFAULT NULL,
    DELETED             TINYINT(1) DEFAULT 0,
    DAT_CREAT           DATETIME DEFAULT CURRENT_TIMESTAMP,
    TIM_UPDATED         DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_ROW),
    UNIQUE KEY UK_T_WC_WIKIDATA_CHARACTER_ID_WIKIDATA (ID_WIKIDATA),
    KEY IDX_T_WC_WIKIDATA_CHARACTER_LABEL_EN (LABEL_EN(255)),
    KEY IDX_T_WC_WIKIDATA_CHARACTER_DELETED (DELETED)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- Staging tables (mirror 02_staging_and_triggers.sql).
-- Full definitions (not CREATE ... LIKE) so this script is self-contained, and
-- the complete set so a live DB whose STG_* tables were dropped is repaired
-- here rather than failing step 108. Keep in sync with the definitions in
-- 02_staging_and_triggers.sql, which stays the canonical source.
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS STG_T_WC_WIKIDATA_MOVIE (
    ID_STG_ROW          BIGINT NOT NULL AUTO_INCREMENT,
    IMPORT_BATCH_ID     VARCHAR(100) DEFAULT NULL,
    SOURCE_FILE         VARCHAR(500) DEFAULT NULL,
    ID_WIKIDATA         VARCHAR(50) NOT NULL,
    LABEL_EN            VARCHAR(500) DEFAULT NULL,
    DESCRIPTION_EN      TEXT DEFAULT NULL,
    LABELS_JSON         LONGTEXT DEFAULT NULL,
    DESCRIPTIONS_JSON   LONGTEXT DEFAULT NULL,
    ROW_STATUS          VARCHAR(20) DEFAULT 'NEW',
    ERROR_MESSAGE       TEXT DEFAULT NULL,
    DAT_IMPORT          DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_STG_ROW),
    KEY IDX_STG_MOVIE_BATCH (IMPORT_BATCH_ID),
    KEY IDX_STG_MOVIE_WIKIDATA (ID_WIKIDATA),
    KEY IDX_STG_MOVIE_STATUS (ROW_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STG_T_WC_WIKIDATA_SERIE (
    ID_STG_ROW          BIGINT NOT NULL AUTO_INCREMENT,
    IMPORT_BATCH_ID     VARCHAR(100) DEFAULT NULL,
    SOURCE_FILE         VARCHAR(500) DEFAULT NULL,
    ID_WIKIDATA         VARCHAR(50) NOT NULL,
    LABEL_EN            VARCHAR(500) DEFAULT NULL,
    DESCRIPTION_EN      TEXT DEFAULT NULL,
    LABELS_JSON         LONGTEXT DEFAULT NULL,
    DESCRIPTIONS_JSON   LONGTEXT DEFAULT NULL,
    ROW_STATUS          VARCHAR(20) DEFAULT 'NEW',
    ERROR_MESSAGE       TEXT DEFAULT NULL,
    DAT_IMPORT          DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_STG_ROW),
    KEY IDX_STG_SERIE_BATCH (IMPORT_BATCH_ID),
    KEY IDX_STG_SERIE_WIKIDATA (ID_WIKIDATA),
    KEY IDX_STG_SERIE_STATUS (ROW_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STG_T_WC_WIKIDATA_PERSON (
    ID_STG_ROW          BIGINT NOT NULL AUTO_INCREMENT,
    IMPORT_BATCH_ID     VARCHAR(100) DEFAULT NULL,
    SOURCE_FILE         VARCHAR(500) DEFAULT NULL,
    ID_WIKIDATA         VARCHAR(50) NOT NULL,
    LABEL_EN            VARCHAR(500) DEFAULT NULL,
    DESCRIPTION_EN      TEXT DEFAULT NULL,
    LABELS_JSON         LONGTEXT DEFAULT NULL,
    DESCRIPTIONS_JSON   LONGTEXT DEFAULT NULL,
    ROW_STATUS          VARCHAR(20) DEFAULT 'NEW',
    ERROR_MESSAGE       TEXT DEFAULT NULL,
    DAT_IMPORT          DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_STG_ROW),
    KEY IDX_STG_PERSON_BATCH (IMPORT_BATCH_ID),
    KEY IDX_STG_PERSON_WIKIDATA (ID_WIKIDATA),
    KEY IDX_STG_PERSON_STATUS (ROW_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STG_T_WC_WIKIDATA_ITEM (
    ID_STG_ROW          BIGINT NOT NULL AUTO_INCREMENT,
    IMPORT_BATCH_ID     VARCHAR(100) DEFAULT NULL,
    SOURCE_FILE         VARCHAR(500) DEFAULT NULL,
    ID_WIKIDATA         VARCHAR(50) NOT NULL,
    LABEL_EN            VARCHAR(500) DEFAULT NULL,
    DESCRIPTION_EN      TEXT DEFAULT NULL,
    LABELS_JSON         LONGTEXT DEFAULT NULL,
    DESCRIPTIONS_JSON   LONGTEXT DEFAULT NULL,
    ROW_STATUS          VARCHAR(20) DEFAULT 'NEW',
    ERROR_MESSAGE       TEXT DEFAULT NULL,
    DAT_IMPORT          DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_STG_ROW),
    KEY IDX_STG_ITEM_BATCH (IMPORT_BATCH_ID),
    KEY IDX_STG_ITEM_WIKIDATA (ID_WIKIDATA),
    KEY IDX_STG_ITEM_STATUS (ROW_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STG_T_WC_WIKIDATA_SEASON (
    ID_STG_ROW          BIGINT NOT NULL AUTO_INCREMENT,
    IMPORT_BATCH_ID     VARCHAR(100) DEFAULT NULL,
    SOURCE_FILE         VARCHAR(500) DEFAULT NULL,
    ID_WIKIDATA         VARCHAR(50) NOT NULL,
    LABEL_EN            VARCHAR(500) DEFAULT NULL,
    DESCRIPTION_EN      TEXT DEFAULT NULL,
    LABELS_JSON         LONGTEXT DEFAULT NULL,
    DESCRIPTIONS_JSON   LONGTEXT DEFAULT NULL,
    ROW_STATUS          VARCHAR(20) DEFAULT 'NEW',
    ERROR_MESSAGE       TEXT DEFAULT NULL,
    DAT_IMPORT          DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_STG_ROW),
    KEY IDX_STG_SEASON_BATCH (IMPORT_BATCH_ID),
    KEY IDX_STG_SEASON_WIKIDATA (ID_WIKIDATA),
    KEY IDX_STG_SEASON_STATUS (ROW_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STG_T_WC_WIKIDATA_EPISODE (
    ID_STG_ROW          BIGINT NOT NULL AUTO_INCREMENT,
    IMPORT_BATCH_ID     VARCHAR(100) DEFAULT NULL,
    SOURCE_FILE         VARCHAR(500) DEFAULT NULL,
    ID_WIKIDATA         VARCHAR(50) NOT NULL,
    LABEL_EN            VARCHAR(500) DEFAULT NULL,
    DESCRIPTION_EN      TEXT DEFAULT NULL,
    LABELS_JSON         LONGTEXT DEFAULT NULL,
    DESCRIPTIONS_JSON   LONGTEXT DEFAULT NULL,
    ROW_STATUS          VARCHAR(20) DEFAULT 'NEW',
    ERROR_MESSAGE       TEXT DEFAULT NULL,
    DAT_IMPORT          DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_STG_ROW),
    KEY IDX_STG_EPISODE_BATCH (IMPORT_BATCH_ID),
    KEY IDX_STG_EPISODE_WIKIDATA (ID_WIKIDATA),
    KEY IDX_STG_EPISODE_STATUS (ROW_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STG_T_WC_WIKIDATA_CHARACTER (
    ID_STG_ROW          BIGINT NOT NULL AUTO_INCREMENT,
    IMPORT_BATCH_ID     VARCHAR(100) DEFAULT NULL,
    SOURCE_FILE         VARCHAR(500) DEFAULT NULL,
    ID_WIKIDATA         VARCHAR(50) NOT NULL,
    LABEL_EN            VARCHAR(500) DEFAULT NULL,
    DESCRIPTION_EN      TEXT DEFAULT NULL,
    LABELS_JSON         LONGTEXT DEFAULT NULL,
    DESCRIPTIONS_JSON   LONGTEXT DEFAULT NULL,
    ROW_STATUS          VARCHAR(20) DEFAULT 'NEW',
    ERROR_MESSAGE       TEXT DEFAULT NULL,
    DAT_IMPORT          DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_STG_ROW),
    KEY IDX_STG_CHARACTER_BATCH (IMPORT_BATCH_ID),
    KEY IDX_STG_CHARACTER_WIKIDATA (ID_WIKIDATA),
    KEY IDX_STG_CHARACTER_STATUS (ROW_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STG_T_WC_WIKIDATA_PROPERTY_METADATA (
    ID_STG_ROW              BIGINT NOT NULL AUTO_INCREMENT,
    IMPORT_BATCH_ID         VARCHAR(100) DEFAULT NULL,
    SOURCE_FILE             VARCHAR(500) DEFAULT NULL,
    ID_PROPERTY             VARCHAR(50) NOT NULL,
    PROPERTY_LABEL          VARCHAR(500) DEFAULT NULL,
    PROPERTY_DESCRIPTION    TEXT DEFAULT NULL,
    WIKIDATA_DATATYPE       VARCHAR(100) DEFAULT NULL,
    LOCAL_VALUE_TYPE        VARCHAR(50) DEFAULT NULL,
    EXPECTED_CHILD_TABLE    VARCHAR(100) DEFAULT NULL,
    FORMATTER_URL           TEXT DEFAULT NULL,
    FORMATTER_URI_FOR_RDF   TEXT DEFAULT NULL,
    IS_SUPPORTED            TINYINT(1) DEFAULT 1,
    IS_ACTIVE               TINYINT(1) DEFAULT 1,
    LAST_SYNC_AT            DATETIME DEFAULT NULL,
    ROW_STATUS              VARCHAR(20) DEFAULT 'NEW',
    ERROR_MESSAGE           TEXT DEFAULT NULL,
    DAT_IMPORT              DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_STG_ROW),
    KEY IDX_STG_PROPERTY_BATCH (IMPORT_BATCH_ID),
    KEY IDX_STG_PROPERTY_ID (ID_PROPERTY),
    KEY IDX_STG_PROPERTY_STATUS (ROW_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STG_T_WC_WIKIDATA_STATEMENT (
    ID_STG_ROW          BIGINT NOT NULL AUTO_INCREMENT,
    IMPORT_BATCH_ID     VARCHAR(100) DEFAULT NULL,
    SOURCE_FILE         VARCHAR(500) DEFAULT NULL,
    ID_STATEMENT        BIGINT NOT NULL,
    ID_WIKIDATA         VARCHAR(50) NOT NULL,
    ID_PROPERTY         VARCHAR(50) NOT NULL,
    STATEMENT_GUID      VARCHAR(255) DEFAULT NULL,
    STATEMENT_HASH      VARCHAR(255) DEFAULT NULL,
    VALUE_TYPE          VARCHAR(50) NOT NULL,
    WIKIDATA_DATATYPE   VARCHAR(100) DEFAULT NULL,
    RANK                VARCHAR(50) DEFAULT NULL,
    IS_BEST_VALUE       TINYINT(1) DEFAULT NULL,
    DISPLAY_ORDER       INT DEFAULT NULL,
    DELETED             TINYINT(1) DEFAULT 0,
    DAT_CREAT           DATETIME DEFAULT NULL,
    TIM_UPDATED         DATETIME DEFAULT NULL,
    ID_CREATOR          BIGINT DEFAULT NULL,
    ID_OWNER            BIGINT DEFAULT NULL,
    ID_USER_UPDATED     BIGINT DEFAULT NULL,
    IMPORT_SOURCE       VARCHAR(100) DEFAULT NULL,
    LAST_SYNC_AT        DATETIME DEFAULT NULL,
    IS_VALID            TINYINT(1) DEFAULT NULL,
    VALIDATION_ERROR    TEXT DEFAULT NULL,
    RAW_VALUE_TEXT      TEXT DEFAULT NULL,
    ROW_STATUS          VARCHAR(20) DEFAULT 'NEW',
    ERROR_MESSAGE       TEXT DEFAULT NULL,
    DAT_IMPORT          DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_STG_ROW),
    KEY IDX_STG_STATEMENT_BATCH (IMPORT_BATCH_ID),
    KEY IDX_STG_STATEMENT_ID (ID_STATEMENT),
    KEY IDX_STG_STATEMENT_STATUS (ROW_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STG_T_WC_WIKIDATA_ITEM_VALUE (
    ID_STG_ROW          BIGINT NOT NULL AUTO_INCREMENT,
    IMPORT_BATCH_ID     VARCHAR(100) DEFAULT NULL,
    ID_STATEMENT        BIGINT NOT NULL,
    ID_ITEM             VARCHAR(50) NOT NULL,
    ROW_STATUS          VARCHAR(20) DEFAULT 'NEW',
    ERROR_MESSAGE       TEXT DEFAULT NULL,
    DAT_IMPORT          DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_STG_ROW),
    KEY IDX_STG_ITEM_VALUE_BATCH (IMPORT_BATCH_ID),
    KEY IDX_STG_ITEM_VALUE_STATEMENT (ID_STATEMENT),
    KEY IDX_STG_ITEM_VALUE_ITEM (ID_ITEM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STG_T_WC_WIKIDATA_STRING_VALUE (
    ID_STG_ROW              BIGINT NOT NULL AUTO_INCREMENT,
    IMPORT_BATCH_ID         VARCHAR(100) DEFAULT NULL,
    ID_STATEMENT            BIGINT NOT NULL,
    VALUE_STRING            LONGTEXT NOT NULL,
    VALUE_STRING_NORMALIZED LONGTEXT DEFAULT NULL,
    LANG_CODE               VARCHAR(20) DEFAULT NULL,
    ROW_STATUS              VARCHAR(20) DEFAULT 'NEW',
    ERROR_MESSAGE           TEXT DEFAULT NULL,
    DAT_IMPORT              DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_STG_ROW),
    KEY IDX_STG_STRING_VALUE_BATCH (IMPORT_BATCH_ID),
    KEY IDX_STG_STRING_VALUE_STATEMENT (ID_STATEMENT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STG_T_WC_WIKIDATA_EXTERNAL_ID_VALUE (
    ID_STG_ROW                      BIGINT NOT NULL AUTO_INCREMENT,
    IMPORT_BATCH_ID                 VARCHAR(100) DEFAULT NULL,
    ID_STATEMENT                    BIGINT NOT NULL,
    VALUE_EXTERNAL_ID               VARCHAR(1000) NOT NULL,
    VALUE_EXTERNAL_ID_NORMALIZED    VARCHAR(1000) DEFAULT NULL,
    FORMATTER_URL                   TEXT DEFAULT NULL,
    FORMATTER_URI_RDF               TEXT DEFAULT NULL,
    VALIDATION_STATUS               VARCHAR(100) DEFAULT NULL,
    ROW_STATUS                      VARCHAR(20) DEFAULT 'NEW',
    ERROR_MESSAGE                   TEXT DEFAULT NULL,
    DAT_IMPORT                      DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_STG_ROW),
    KEY IDX_STG_EXTERNAL_ID_BATCH (IMPORT_BATCH_ID),
    KEY IDX_STG_EXTERNAL_ID_STATEMENT (ID_STATEMENT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STG_T_WC_WIKIDATA_MEDIA_VALUE (
    ID_STG_ROW          BIGINT NOT NULL AUTO_INCREMENT,
    IMPORT_BATCH_ID     VARCHAR(100) DEFAULT NULL,
    ID_STATEMENT        BIGINT NOT NULL,
    FILE_NAME           VARCHAR(1000) NOT NULL,
    MEDIA_REPOSITORY    VARCHAR(100) DEFAULT NULL,
    FILE_PAGE_URL       TEXT DEFAULT NULL,
    FILE_DIRECT_URL     TEXT DEFAULT NULL,
    MIME_TYPE           VARCHAR(255) DEFAULT NULL,
    FILE_EXTENSION      VARCHAR(50) DEFAULT NULL,
    ROW_STATUS          VARCHAR(20) DEFAULT 'NEW',
    ERROR_MESSAGE       TEXT DEFAULT NULL,
    DAT_IMPORT          DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_STG_ROW),
    KEY IDX_STG_MEDIA_VALUE_BATCH (IMPORT_BATCH_ID),
    KEY IDX_STG_MEDIA_VALUE_STATEMENT (ID_STATEMENT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STG_T_WC_WIKIDATA_TIME_VALUE (
    ID_STG_ROW          BIGINT NOT NULL AUTO_INCREMENT,
    IMPORT_BATCH_ID     VARCHAR(100) DEFAULT NULL,
    ID_STATEMENT        BIGINT NOT NULL,
    RAW_TIME_VALUE      VARCHAR(100) DEFAULT NULL,
    TIME_PRECISION      INT DEFAULT NULL,
    CALENDAR_MODEL      VARCHAR(255) DEFAULT NULL,
    TIMEZONE_OFFSET     INT DEFAULT NULL,
    YEAR_VALUE          BIGINT DEFAULT NULL,
    MONTH_VALUE         INT DEFAULT NULL,
    DAY_VALUE           INT DEFAULT NULL,
    DATE_START          DATE DEFAULT NULL,
    DATE_END            DATE DEFAULT NULL,
    ROW_STATUS          VARCHAR(20) DEFAULT 'NEW',
    ERROR_MESSAGE       TEXT DEFAULT NULL,
    DAT_IMPORT          DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_STG_ROW),
    KEY IDX_STG_TIME_VALUE_BATCH (IMPORT_BATCH_ID),
    KEY IDX_STG_TIME_VALUE_STATEMENT (ID_STATEMENT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STG_T_WC_WIKIDATA_QUANTITY_VALUE (
    ID_STG_ROW          BIGINT NOT NULL AUTO_INCREMENT,
    IMPORT_BATCH_ID     VARCHAR(100) DEFAULT NULL,
    ID_STATEMENT        BIGINT NOT NULL,
    AMOUNT              DECIMAL(30,10) DEFAULT NULL,
    UNIT_ID_WIKIDATA    VARCHAR(50) DEFAULT NULL,
    LOWER_BOUND         DECIMAL(30,10) DEFAULT NULL,
    UPPER_BOUND         DECIMAL(30,10) DEFAULT NULL,
    AMOUNT_NORMALIZED   DECIMAL(30,10) DEFAULT NULL,
    DISPLAY_VALUE       VARCHAR(255) DEFAULT NULL,
    ROW_STATUS          VARCHAR(20) DEFAULT 'NEW',
    ERROR_MESSAGE       TEXT DEFAULT NULL,
    DAT_IMPORT          DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_STG_ROW),
    KEY IDX_STG_QUANTITY_VALUE_BATCH (IMPORT_BATCH_ID),
    KEY IDX_STG_QUANTITY_VALUE_STATEMENT (ID_STATEMENT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STG_T_WC_WIKIDATA_STATEMENT_QUALIFIER (
    ID_STG_ROW              BIGINT NOT NULL AUTO_INCREMENT,
    IMPORT_BATCH_ID         VARCHAR(100) DEFAULT NULL,
    SOURCE_FILE             VARCHAR(500) DEFAULT NULL,
    ID_STATEMENT_QUALIFIER  BIGINT NOT NULL,
    ID_STATEMENT            BIGINT NOT NULL,
    ID_QUALIFIER_PROPERTY   VARCHAR(50) NOT NULL,
    QUALIFIER_HASH          VARCHAR(255) DEFAULT NULL,
    VALUE_TYPE              VARCHAR(50) NOT NULL,
    WIKIDATA_DATATYPE       VARCHAR(100) DEFAULT NULL,
    DISPLAY_ORDER           INT DEFAULT NULL,
    DELETED                 TINYINT(1) DEFAULT 0,
    DAT_CREAT               DATETIME DEFAULT NULL,
    TIM_UPDATED             DATETIME DEFAULT NULL,
    ID_CREATOR              BIGINT DEFAULT NULL,
    ID_OWNER                BIGINT DEFAULT NULL,
    ID_USER_UPDATED         BIGINT DEFAULT NULL,
    IMPORT_SOURCE           VARCHAR(100) DEFAULT NULL,
    LAST_SYNC_AT            DATETIME DEFAULT NULL,
    IS_VALID                TINYINT(1) DEFAULT NULL,
    VALIDATION_ERROR        TEXT DEFAULT NULL,
    RAW_VALUE_TEXT          TEXT DEFAULT NULL,
    ROW_STATUS              VARCHAR(20) DEFAULT 'NEW',
    ERROR_MESSAGE           TEXT DEFAULT NULL,
    DAT_IMPORT              DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_STG_ROW),
    KEY IDX_STG_STATEMENT_QUALIFIER_BATCH (IMPORT_BATCH_ID),
    KEY IDX_STG_STATEMENT_QUALIFIER_ID (ID_STATEMENT_QUALIFIER),
    KEY IDX_STG_STATEMENT_QUALIFIER_STATEMENT (ID_STATEMENT),
    KEY IDX_STG_STATEMENT_QUALIFIER_STATUS (ROW_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STG_T_WC_WIKIDATA_QUALIFIER_ITEM_VALUE (
    ID_STG_ROW              BIGINT NOT NULL AUTO_INCREMENT,
    IMPORT_BATCH_ID         VARCHAR(100) DEFAULT NULL,
    ID_STATEMENT_QUALIFIER  BIGINT NOT NULL,
    ID_ITEM                 VARCHAR(50) NOT NULL,
    ROW_STATUS              VARCHAR(20) DEFAULT 'NEW',
    ERROR_MESSAGE           TEXT DEFAULT NULL,
    DAT_IMPORT              DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_STG_ROW),
    KEY IDX_STG_QUALIFIER_ITEM_VALUE_BATCH (IMPORT_BATCH_ID),
    KEY IDX_STG_QUALIFIER_ITEM_VALUE_PARENT (ID_STATEMENT_QUALIFIER),
    KEY IDX_STG_QUALIFIER_ITEM_VALUE_ITEM (ID_ITEM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STG_T_WC_WIKIDATA_QUALIFIER_STRING_VALUE (
    ID_STG_ROW              BIGINT NOT NULL AUTO_INCREMENT,
    IMPORT_BATCH_ID         VARCHAR(100) DEFAULT NULL,
    ID_STATEMENT_QUALIFIER  BIGINT NOT NULL,
    VALUE_STRING            LONGTEXT NOT NULL,
    VALUE_STRING_NORMALIZED LONGTEXT DEFAULT NULL,
    LANG_CODE               VARCHAR(20) DEFAULT NULL,
    ROW_STATUS              VARCHAR(20) DEFAULT 'NEW',
    ERROR_MESSAGE           TEXT DEFAULT NULL,
    DAT_IMPORT              DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_STG_ROW),
    KEY IDX_STG_QUALIFIER_STRING_VALUE_BATCH (IMPORT_BATCH_ID),
    KEY IDX_STG_QUALIFIER_STRING_VALUE_PARENT (ID_STATEMENT_QUALIFIER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STG_T_WC_WIKIDATA_QUALIFIER_EXTERNAL_ID_VALUE (
    ID_STG_ROW                      BIGINT NOT NULL AUTO_INCREMENT,
    IMPORT_BATCH_ID                 VARCHAR(100) DEFAULT NULL,
    ID_STATEMENT_QUALIFIER          BIGINT NOT NULL,
    VALUE_EXTERNAL_ID               VARCHAR(1000) NOT NULL,
    VALUE_EXTERNAL_ID_NORMALIZED    VARCHAR(1000) DEFAULT NULL,
    FORMATTER_URL                   TEXT DEFAULT NULL,
    FORMATTER_URI_RDF               TEXT DEFAULT NULL,
    VALIDATION_STATUS               VARCHAR(100) DEFAULT NULL,
    ROW_STATUS                      VARCHAR(20) DEFAULT 'NEW',
    ERROR_MESSAGE                   TEXT DEFAULT NULL,
    DAT_IMPORT                      DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_STG_ROW),
    KEY IDX_STG_QUALIFIER_EXTERNAL_ID_BATCH (IMPORT_BATCH_ID),
    KEY IDX_STG_QUALIFIER_EXTERNAL_ID_PARENT (ID_STATEMENT_QUALIFIER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STG_T_WC_WIKIDATA_QUALIFIER_MEDIA_VALUE (
    ID_STG_ROW              BIGINT NOT NULL AUTO_INCREMENT,
    IMPORT_BATCH_ID         VARCHAR(100) DEFAULT NULL,
    ID_STATEMENT_QUALIFIER  BIGINT NOT NULL,
    FILE_NAME               VARCHAR(1000) NOT NULL,
    MEDIA_REPOSITORY        VARCHAR(100) DEFAULT NULL,
    FILE_PAGE_URL           TEXT DEFAULT NULL,
    FILE_DIRECT_URL         TEXT DEFAULT NULL,
    MIME_TYPE               VARCHAR(255) DEFAULT NULL,
    FILE_EXTENSION          VARCHAR(50) DEFAULT NULL,
    ROW_STATUS              VARCHAR(20) DEFAULT 'NEW',
    ERROR_MESSAGE           TEXT DEFAULT NULL,
    DAT_IMPORT              DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_STG_ROW),
    KEY IDX_STG_QUALIFIER_MEDIA_VALUE_BATCH (IMPORT_BATCH_ID),
    KEY IDX_STG_QUALIFIER_MEDIA_VALUE_PARENT (ID_STATEMENT_QUALIFIER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STG_T_WC_WIKIDATA_QUALIFIER_TIME_VALUE (
    ID_STG_ROW              BIGINT NOT NULL AUTO_INCREMENT,
    IMPORT_BATCH_ID         VARCHAR(100) DEFAULT NULL,
    ID_STATEMENT_QUALIFIER  BIGINT NOT NULL,
    RAW_TIME_VALUE          VARCHAR(100) DEFAULT NULL,
    TIME_PRECISION          INT DEFAULT NULL,
    CALENDAR_MODEL          VARCHAR(255) DEFAULT NULL,
    TIMEZONE_OFFSET         INT DEFAULT NULL,
    YEAR_VALUE              BIGINT DEFAULT NULL,
    MONTH_VALUE             INT DEFAULT NULL,
    DAY_VALUE               INT DEFAULT NULL,
    DATE_START              DATE DEFAULT NULL,
    DATE_END                DATE DEFAULT NULL,
    ROW_STATUS              VARCHAR(20) DEFAULT 'NEW',
    ERROR_MESSAGE           TEXT DEFAULT NULL,
    DAT_IMPORT              DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_STG_ROW),
    KEY IDX_STG_QUALIFIER_TIME_VALUE_BATCH (IMPORT_BATCH_ID),
    KEY IDX_STG_QUALIFIER_TIME_VALUE_PARENT (ID_STATEMENT_QUALIFIER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STG_T_WC_WIKIDATA_QUALIFIER_QUANTITY_VALUE (
    ID_STG_ROW              BIGINT NOT NULL AUTO_INCREMENT,
    IMPORT_BATCH_ID         VARCHAR(100) DEFAULT NULL,
    ID_STATEMENT_QUALIFIER  BIGINT NOT NULL,
    AMOUNT                  DECIMAL(30,10) DEFAULT NULL,
    UNIT_ID_WIKIDATA        VARCHAR(50) DEFAULT NULL,
    LOWER_BOUND             DECIMAL(30,10) DEFAULT NULL,
    UPPER_BOUND             DECIMAL(30,10) DEFAULT NULL,
    AMOUNT_NORMALIZED       DECIMAL(30,10) DEFAULT NULL,
    DISPLAY_VALUE           VARCHAR(255) DEFAULT NULL,
    ROW_STATUS              VARCHAR(20) DEFAULT 'NEW',
    ERROR_MESSAGE           TEXT DEFAULT NULL,
    DAT_IMPORT              DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_STG_ROW),
    KEY IDX_STG_QUALIFIER_QUANTITY_VALUE_BATCH (IMPORT_BATCH_ID),
    KEY IDX_STG_QUALIFIER_QUANTITY_VALUE_PARENT (ID_STATEMENT_QUALIFIER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STG_T_WC_WIKIDATA_MEDIA_RESOURCE (
    ID_STG_ROW                      BIGINT NOT NULL AUTO_INCREMENT,
    IMPORT_BATCH_ID                 VARCHAR(100) DEFAULT NULL,
    ID_MEDIA_RESOURCE               BIGINT DEFAULT NULL,
    ID_STATEMENT                    BIGINT NOT NULL,
    ID_WIKIDATA                     VARCHAR(50) NOT NULL,
    ID_PROPERTY                     VARCHAR(50) NOT NULL,
    SOURCE_PLATFORM                 VARCHAR(50) NOT NULL,
    SOURCE_IDENTIFIER               VARCHAR(1000) NOT NULL,
    SOURCE_IDENTIFIER_NORMALIZED    VARCHAR(1000) DEFAULT NULL,
    RESOURCE_KEY                    VARCHAR(1200) DEFAULT NULL,
    RESOURCE_KIND                   VARCHAR(50) DEFAULT NULL,
    CONTENT_ROLE                    VARCHAR(50) DEFAULT NULL,
    CONTENT_SCOPE                   VARCHAR(50) DEFAULT NULL,
    LANG_CODE                       VARCHAR(20) DEFAULT NULL,
    IS_PREFERRED_RESOURCE           TINYINT(1) DEFAULT 0,
    IS_PRIMARY_FOR_ENTITY           TINYINT(1) DEFAULT 0,
    SOURCE_PRIORITY                 INT DEFAULT NULL,
    QUALITY_SCORE                   DECIMAL(10,4) DEFAULT NULL,
    RESOURCE_TITLE                  VARCHAR(1000) DEFAULT NULL,
    RESOURCE_SUBTITLE               VARCHAR(1000) DEFAULT NULL,
    RESOURCE_DESCRIPTION            TEXT DEFAULT NULL,
    CHANNEL_OR_COLLECTION           VARCHAR(1000) DEFAULT NULL,
    THUMBNAIL_URL_PRIMARY           TEXT DEFAULT NULL,
    DURATION_SECONDS                INT DEFAULT NULL,
    WIDTH                           INT DEFAULT NULL,
    HEIGHT                          INT DEFAULT NULL,
    MIME_TYPE_PRIMARY               VARCHAR(255) DEFAULT NULL,
    FILE_EXTENSION_PRIMARY          VARCHAR(50) DEFAULT NULL,
    FILE_SIZE_PRIMARY               BIGINT DEFAULT NULL,
    IS_PLAYABLE                     TINYINT(1) DEFAULT 0,
    IS_DOWNLOADABLE                 TINYINT(1) DEFAULT 0,
    IS_EMBEDDABLE                   TINYINT(1) DEFAULT 0,
    IS_ACTIVE                       TINYINT(1) DEFAULT 1,
    IS_VALID                        TINYINT(1) DEFAULT NULL,
    RESOLUTION_STATUS               VARCHAR(50) DEFAULT NULL,
    RESOLUTION_METHOD               VARCHAR(100) DEFAULT NULL,
    LAST_RESOLVED_AT                DATETIME DEFAULT NULL,
    LAST_CHECKED_AT                 DATETIME DEFAULT NULL,
    LAST_SUCCESS_AT                 DATETIME DEFAULT NULL,
    ERROR_CODE                      VARCHAR(100) DEFAULT NULL,
    ERROR_MESSAGE                   TEXT DEFAULT NULL,
    DISCOVERED_AT                   DATETIME DEFAULT NULL,
    TIM_UPDATED                     DATETIME DEFAULT NULL,
    ID_USER_UPDATED                 BIGINT DEFAULT NULL,
    DELETED                         TINYINT(1) DEFAULT 0,
    ROW_STATUS                      VARCHAR(20) DEFAULT 'NEW',
    DAT_IMPORT                      DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_STG_ROW),
    KEY IDX_STG_MEDIA_RESOURCE_BATCH (IMPORT_BATCH_ID),
    KEY IDX_STG_MEDIA_RESOURCE_STATEMENT (ID_STATEMENT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STG_T_WC_WIKIDATA_MEDIA_RESOURCE_URL (
    ID_STG_ROW              BIGINT NOT NULL AUTO_INCREMENT,
    IMPORT_BATCH_ID         VARCHAR(100) DEFAULT NULL,
    ID_MEDIA_RESOURCE_URL   BIGINT DEFAULT NULL,
    ID_MEDIA_RESOURCE       BIGINT NOT NULL,
    URL_TYPE                VARCHAR(50) NOT NULL,
    URL_ROLE                VARCHAR(100) DEFAULT NULL,
    DISPLAY_ORDER           INT DEFAULT NULL,
    IS_CANONICAL            TINYINT(1) DEFAULT 0,
    IS_PREFERRED            TINYINT(1) DEFAULT 0,
    IS_DIRECT_FILE          TINYINT(1) DEFAULT 0,
    URL                     TEXT NOT NULL,
    URL_NORMALIZED          TEXT DEFAULT NULL,
    URL_HASH                CHAR(64) DEFAULT NULL,
    MIME_TYPE               VARCHAR(255) DEFAULT NULL,
    FILE_EXTENSION          VARCHAR(50) DEFAULT NULL,
    FILE_SIZE               BIGINT DEFAULT NULL,
    WIDTH                   INT DEFAULT NULL,
    HEIGHT                  INT DEFAULT NULL,
    BITRATE                 INT DEFAULT NULL,
    FRAME_RATE              DECIMAL(10,4) DEFAULT NULL,
    VIDEO_CODEC             VARCHAR(255) DEFAULT NULL,
    AUDIO_CODEC             VARCHAR(255) DEFAULT NULL,
    DURATION_SECONDS        INT DEFAULT NULL,
    QUALITY_LABEL           VARCHAR(100) DEFAULT NULL,
    IS_ACTIVE               TINYINT(1) DEFAULT 1,
    IS_PLAYABLE             TINYINT(1) DEFAULT 0,
    IS_DOWNLOADABLE         TINYINT(1) DEFAULT 0,
    IS_EMBEDDABLE           TINYINT(1) DEFAULT 0,
    IS_PUBLIC               TINYINT(1) DEFAULT NULL,
    HTTP_STATUS             INT DEFAULT NULL,
    CONTENT_TYPE_HEADER     VARCHAR(255) DEFAULT NULL,
    REDIRECT_URL            TEXT DEFAULT NULL,
    LAST_CHECKED_AT         DATETIME DEFAULT NULL,
    LAST_SUCCESS_AT         DATETIME DEFAULT NULL,
    CHECK_COUNT             INT DEFAULT 0,
    FAIL_COUNT              INT DEFAULT 0,
    ERROR_CODE              VARCHAR(100) DEFAULT NULL,
    ERROR_MESSAGE           TEXT DEFAULT NULL,
    DISCOVERED_AT           DATETIME DEFAULT NULL,
    TIM_UPDATED             DATETIME DEFAULT NULL,
    DELETED                 TINYINT(1) DEFAULT 0,
    ROW_STATUS              VARCHAR(20) DEFAULT 'NEW',
    DAT_IMPORT              DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_STG_ROW),
    KEY IDX_STG_MEDIA_URL_BATCH (IMPORT_BATCH_ID),
    KEY IDX_STG_MEDIA_URL_RESOURCE (ID_MEDIA_RESOURCE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STG_T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK (
    ID_STG_ROW                  BIGINT NOT NULL AUTO_INCREMENT,
    IMPORT_BATCH_ID             VARCHAR(100) DEFAULT NULL,
    ID_MEDIA_RESOURCE_CHECK     BIGINT DEFAULT NULL,
    ID_MEDIA_RESOURCE           BIGINT NOT NULL,
    ID_MEDIA_RESOURCE_URL       BIGINT DEFAULT NULL,
    CHECK_SCOPE                 VARCHAR(50) NOT NULL,
    CHECK_TYPE                  VARCHAR(100) NOT NULL,
    CHECK_REASON                VARCHAR(100) DEFAULT NULL,
    CHECK_STATUS                VARCHAR(50) NOT NULL,
    RESULT_CODE                 VARCHAR(100) DEFAULT NULL,
    RESULT_SUMMARY              VARCHAR(1000) DEFAULT NULL,
    HTTP_STATUS                 INT DEFAULT NULL,
    CONTENT_TYPE_HEADER         VARCHAR(255) DEFAULT NULL,
    REDIRECT_URL                TEXT DEFAULT NULL,
    RESPONSE_TIME_MS            INT DEFAULT NULL,
    OBSERVED_URL                TEXT DEFAULT NULL,
    OBSERVED_MIME_TYPE          VARCHAR(255) DEFAULT NULL,
    OBSERVED_FILE_SIZE          BIGINT DEFAULT NULL,
    OBSERVED_DURATION_SECONDS   INT DEFAULT NULL,
    OBSERVED_WIDTH              INT DEFAULT NULL,
    OBSERVED_HEIGHT             INT DEFAULT NULL,
    ERROR_CODE                  VARCHAR(100) DEFAULT NULL,
    ERROR_MESSAGE               TEXT DEFAULT NULL,
    RAW_RESPONSE_SNIPPET        TEXT DEFAULT NULL,
    CHECKED_AT                  DATETIME DEFAULT NULL,
    CHECKER_NAME                VARCHAR(100) DEFAULT NULL,
    ROW_STATUS                  VARCHAR(20) DEFAULT 'NEW',
    DAT_IMPORT                  DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_STG_ROW),
    KEY IDX_STG_MEDIA_CHECK_BATCH (IMPORT_BATCH_ID),
    KEY IDX_STG_MEDIA_CHECK_RESOURCE (ID_MEDIA_RESOURCE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- P279 subclass graph, added 2026-08-16.
--
-- pass1 has always written /shared/pass1/subclass_edges.jsonl; nothing loaded it,
-- so the class graph was invisible to SQL and no hierarchical question could be
-- answered. Both the target table and its staging table are created here because
-- 01_create_schema.sql only ever runs on a fresh database.
--
-- Populating it needs no ETL re-run when the pass1 directory of the last run is
-- still on disk: step 108 picks the file up through load_staging_jsonl.py.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS T_WC_WIKIDATA_SUBCLASS (
    ID_CHILD             VARCHAR(50) NOT NULL,
    ID_PARENT            VARCHAR(50) NOT NULL,
    DELETED              TINYINT(1) DEFAULT 0,
    DAT_CREAT            DATETIME DEFAULT CURRENT_TIMESTAMP,
    TIM_UPDATED          DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IMPORT_BATCH_ID      VARCHAR(100) DEFAULT NULL,
    PRIMARY KEY (ID_CHILD, ID_PARENT),
    KEY IDX_T_WC_WIKIDATA_SUBCLASS_PARENT (ID_PARENT),
    KEY IDX_T_WC_WIKIDATA_SUBCLASS_BATCH (IMPORT_BATCH_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STG_T_WC_WIKIDATA_SUBCLASS (
    ID_STG_ROW BIGINT NOT NULL AUTO_INCREMENT,
    IMPORT_BATCH_ID VARCHAR(100) DEFAULT NULL,
    SOURCE_FILE VARCHAR(500) DEFAULT NULL,
    ID_CHILD VARCHAR(50) NOT NULL,
    ID_PARENT VARCHAR(50) NOT NULL,
    ROW_STATUS VARCHAR(20) DEFAULT 'NEW',
    ERROR_MESSAGE TEXT DEFAULT NULL,
    DAT_IMPORT DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_STG_ROW),
    KEY IDX_STG_SUBCLASS_BATCH (IMPORT_BATCH_ID),
    KEY IDX_STG_SUBCLASS_STATUS (ROW_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- Widen YEAR_VALUE to BIGINT: Wikidata stores astronomical/geological years
-- (e.g. Big Bang +13800000000) that overflow signed INT (max 2147483647),
-- which raised error 1264 "Out of range value for column 'YEAR_VALUE'".
-- ALTER ... MODIFY to the same type is a harmless no-op, so this stays idempotent.
-- ----------------------------------------------------------------------------
ALTER TABLE T_WC_WIKIDATA_TIME_VALUE               MODIFY COLUMN YEAR_VALUE BIGINT DEFAULT NULL;
ALTER TABLE T_WC_WIKIDATA_QUALIFIER_TIME_VALUE     MODIFY COLUMN YEAR_VALUE BIGINT DEFAULT NULL;
ALTER TABLE STG_T_WC_WIKIDATA_TIME_VALUE           MODIFY COLUMN YEAR_VALUE BIGINT DEFAULT NULL;
ALTER TABLE STG_T_WC_WIKIDATA_QUALIFIER_TIME_VALUE MODIFY COLUMN YEAR_VALUE BIGINT DEFAULT NULL;
